### ISSUE TITLE
mintinstall ignores system proxy

### ISSUE THREAD

**Issue by liorbp** [linuxmint/mintinstall#103]
Not too much to describe here...
mintinstall just ignores the proxy (http/s and socks) I configured on my Linux Mint 17.3...
When I was trying to change the packages mirror to a local one I noticed that mintinstall sends a request to: http://geoip.ubuntu.com/lookup and the request just don't go through the system predefined proxy setting.

**Comment by clefebvre** [comment]
Following the recent mintinstall revamp on git master, we no longer run in root mode so this can be closed.
