### ISSUE TITLE
LMDE2 - Installer crashed

### ISSUE THREAD

**Issue by kmkom** [linuxmint/mintinstall#104]
Installing LMDE2-Cinnamon in VirtualBox:

Host: Mint 17.3, Cinnamon
Virtual-Box: 5.0.20

When I install LMDE2-Cinnamon and the installer comes to the disk partition task a dialog appears (see pic10) and the option "No" is already selected. But if I press "No" in the next step a crash-dialog box appears (pic11). I would expect that the installer jumps to the manual part of the disk partition dialog. 

![pic10](https://cloud.githubusercontent.com/assets/15555865/15273535/11258c3e-1a9d-11e6-9aaf-60c02fa82634.png)
![pic11](https://cloud.githubusercontent.com/assets/15555865/15273536/1723049a-1a9d-11e6-80be-efd920e8ee4c.png)

**Comment by xenopeek** [comment]
mintinstall is the Software Manager program. This isn't a good place for this issue and I suggest you close it.

Better ask for support on the Linux Mint forums here https://forums.linuxmint.com/viewforum.php?f=237 so those knowledgeable about installation issues can help figure it out. It would help if you had a screenshot in English or you can translate the non-English text. If it is a reproducible bug I'll pick it up from the forum.
