### ISSUE TITLE
Capture Application Version in User Feedback

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/mintinstall#106]
Building on the below*\* idea, when user submits a comment, the corresponding version of the should be captured. At the moment only date is shown.

*\* https://community.linuxmint.com/idea/view/6393

**Comment by xenopeek** [comment]
Since Linux Mint 18.3 users can no longer review in mintinstall itself. Instead the review button opens the software's page on the community website, in the default web browser. The review is done there.
