### ISSUE TITLE
Unable to continue installation of Linux Mint 18

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintinstall#107]
I've not found more appropriate place to report bug, so reporting here.
Steps to repro:
1. Start LM XFCE 18 installation
2. Mount some partition in live system (sda1 e.g.)
3. In installation details select sda1 for one of installation partitions ("/" e.g.)
4. After hitting isntall this window pops up, both buttons don't do anything.
![screenshot_2016-08-14_19-23-55](https://cloud.githubusercontent.com/assets/7345761/17651355/fc235a0a-6254-11e6-94aa-46a8a1d237fc.png)

**Comment by xenopeek** [comment]
mintinstall is the Software Manager program. This isn't a good place for this issue and I suggest you close it.

Better ask for support on the Linux Mint forums here https://forums.linuxmint.com/viewforum.php?f=46 so those knowledgable about installation issues can help figure it out. It would help if you had a screenshot in English or you can translate what it says. If it is a reproducible bug I'll pick it up from the forum.

**Comment by Yanpas** [comment]
@xenopeek here is the translation 
![default](https://cloud.githubusercontent.com/assets/7345761/17948665/735acb32-6a5a-11e6-8de2-8d34a414141d.png)
