### ISSUE TITLE
Ask for the password only when actually installing software

### ISSUE THREAD

**Issue by sphh** [linuxmint/mintinstall#109]
Hi,

At the moment mintinstall asks for the user password to get root privileges at the start up. I would very much prefer to be asked only when actually installing some software. Why?
- mintinstall is a very valuable tool to search for software: I often end up starting mintinstall to look for a certain piece of software using the search feature. Adding the password every time is a bit annoying.
- A user who cannot gain root privileges cannot use mintinstall in such a way.

Would you consider changing the start up sequence?

Thanks,
Stephan

**Comment by xenopeek** [comment]
That would be a reversal of the change done for Linux Mint 14 back in 2012 https://www.linuxmint.com/rel_nadia_whatsnew.php#mintinstall (commit https://github.com/linuxmint/mintinstall/commit/1873b13e5631b909c00845a272b51507b12c617a) to make it so you only need to give your password once to authorize Software Manager.

**Comment by JosephMcc** [comment]
I'll go ahead and label this as a feature request but I do believe this was changed because it was asked for by users.

**Comment by sphh** [comment]
Thanks for your answers! May I clarify my idea?

Behaviour pre-commit 1873b13:
- mintinstall started without a password request
- every time you clicked "install" mintinstall asked for your password

Behaviour since commit 1873b13:
- when mintinstall starts it asks for your password
- you can click install without being asked for your password

Behaviour I would prefer:
- mintinstall starts without a password request (so that every user can browse the available software)
- the first time you click "install" mintinstall asked for your password to gain root privileges
- any subsequent click on "install" does not ask for your password again and simply installs the package(s)

Does that make sense?

**Comment by JosephMcc** [comment]
Yes. That would be a nice way to handle it.

**Comment by JosephMcc** [comment]
This is now implemented on git master.

**Comment by sphh** [comment]
Thanks, that's great! I'm looking forward for it to trickle down to my desktop.
