### ISSUE TITLE
Software Manager randomly crashes when launched

### ISSUE THREAD

**Issue by Odyseus** [linuxmint/mintinstall#110]
Hello, everybody.

I'm experiencing random crashes every time I launch the Software Manager. There are several people also reporting the same crashes on different desktop environments in [this forum topic](https://forums.linuxmint.com/viewtopic.php?f=208&t=228311).

When launched from a terminal, and the Software Manager opens normally, I see this output on the terminal:

```
$ gksu mintinstall
Vector smash protection is enabled.
add_categories took 141.503 ms
build_matched_packages took 0.173 ms
add_packages took 4948.597 ms
add_reviews took 1127.644 ms
__init__ took 8287.479 ms
show_category took 51.042 ms
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
Killed
```

When the Software Manager crashes, I see this output on terminal:

```
$ gksu mintinstall
Vector smash protection is enabled.
add_categories took 0.835 ms
build_matched_packages took 0.173 ms
add_packages took 4936.035 ms
add_reviews took 1043.324 ms
__init__ took 6585.918 ms
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
Segmentation fault
```

And this error in **/var/log/syslog**:

```
kernel: [18204.752748] mintinstall[31485]: segfault at 8 ip 00007f91d72d581d sp 00007ffee6d28160 error 4 in libGL.so.340.96[7f91d7227000+c7000]
```
### My system information
- **Operating System:** Linux Mint 18 Cinnamon 64-bit
- **Cinnamon Version:** 3.0.7
- **Linux Kernel:** 4.4.0-21-generic
- **Processor:** AMD Phenom(tm) II X4 955 Processor × 4
- **Memory:** 6.8 GiB
- **Hard Drives:** 1936.6 GB
- **Graphics Card:** NVIDIA Corporation G94 [GeForce 9600 GT]

**Comment by Prsman** [comment]
I am having the same problem with a twist.  If I launch Software Manager from the terminal, it will start. 
The terminal will hang after the _init_took x - line is displayed.  After I close Software manager I get the OpenJDK line with killed at the end.  Same error in /var/log/syslog.

**Comment by iainrs** [comment]
Likewise - symptoms as above.
Sometimes fails from menu (Whisker) and works from command line.


**System:**
Kernel: 4.4.0-34-generic x86_64 (64 bit)
           Desktop: Xfce 4.12.3 Distro: Linux Mint 18 Sarah

**Machine:**
Mobo: ASUSTeK model: P7P55D LE v: Rev 1.xx
           Bios: American Megatrends v: 2003 date: 12/16/2010

**CPU:**
Quad core Intel Core i5 750 (-MCP-) cache: 8192 KB 
           clock speeds: max: 2668 MHz 1: 1200 MHz 2: 1200 MHz 3: 1200 MHz
           4: 1200 MHz

**Graphics:**
Card: NVIDIA G94 [GeForce 9600 GT]
           Display Server: X.Org 1.18.3 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1680x1050@59.95hz, 1920x1080@60.00hz
           GLX Renderer: GeForce 9600 GT/PCIe/SSE2
           GLX Version: 3.3.0 NVIDIA 340.96

**Comment by clefebvre** [comment]
@Odyseus can you get a stack trace with gdb?

**Comment by iainrs** [comment]
Still failing with 18.1 xfce  (see https://forums.linuxmint.com/viewtopic.php?f=208&t=228311)

**Comment by LampLighter1440** [comment]
_More information hope it adds to the knowledge:_

**Scenarios**
This issue does occur on Nvidia 304.134
This issue has not occurred (for me) on Nouveau drivers
The issue occurs using both Software Manager and using mintinstall directly

**Failures**
When the manager fails to stay open there are one of two types of notifications
1) Segment Failure - which originates in the Nvidia package containing libGL.so.304.134 and is reported by the kernel as a user-mode error
2) Real-time signal 0 - which 'visually' looks just like the failure on the desktop but does not generate any syslog entries


**Hardware**
Linux Mint 18.1, Kernel 4.4.0-62, xfce desktop,
Asus Motherboard, Intel CPU, 4GB Ram 
Nvidia 210 Graphics card, Legacy 304.134 graphic driver

**Comment by iainrs** [comment]
Thanks LampLighter1440.

I was on Nvidia 340.1.0.1 (upgrade from 304. with 18.1  ?)

changed to nouveau (1.1.0.12) - had to reset dual-monitor settings 
but mintinstall works.
I'll continue with nouveau  and see what happens.

see Driver Manager image :+1: 
![driver manager_097](https://cloud.githubusercontent.com/assets/5394974/22864470/078be4dc-f14a-11e6-86d5-7194822ee38e.png)

Thanks for your info.

**Comment by clefebvre** [comment]
Following the recent mintinstall revamp on git master, we no longer use Webkit/GL, so this can be closed.
