### ISSUE TITLE
Elevate Privs button (open w/o password)

### ISSUE THREAD

**Issue by crimsonmane** [linuxmint/mintinstall#111]
Software Manager should open without asking for a password, and have an "elevate privs" button for install/uninstall so that admins do not have to enter password every time for current session. Or at least have it as a preference setting. I wouldn't mind keeping the current method as long as I could change it.

How should users other than the admin browse apps? Suppose kids want to browse games and then ask me to install one.

**Comment by JosephMcc** [comment]
The application now opens and allows browsing without a password. It only requests a password when attempting to actually install/remove something.
