### ISSUE TITLE
package cannot be deleted: an other application is using APT: DPKG

### ISSUE THREAD

**Issue by choss38** [linuxmint/mintinstall#113]
Hi,

I recently always have a message when I want to install or delete a software: "package cannot be installed or deleted : an other application is using APT: DPKG."
But It ever works ! Software are installed or deleted !
I dont understand because I dont use in the same time Synaptic and others apt, dpkg...

I tried to remove some file named 'lock' in subfolder of /var (/var/lib/apt/lists/lock or /var/lib/dpkg/lock)
but It didn't change anything.

Linux Mint 18 Cinnamon 64bit
Kernel 4.4.0.21
Mintinstall 7.7.4

**Comment by Odyseus** [comment]
Hello, @choss38.
Check for the new update for mintinstall (7.7.5). That problem that you described was already fixed by that new version. Give it a try.

**Comment by choss38** [comment]
Oh, ok, I'm sorry !
It's ok with ver. 7.7.5.
Thank you.
