### ISSUE TITLE
Category View - Icon Issue

### ISSUE THREAD

**Issue by AugustZellmer** [linuxmint/mintinstall#116]
I recently installed Linux Mint, and then installed the Papirus icon pack. Unfortunately, this icon pack is missing some of the icons that MintInstall needs, so MintInstall fell back to some pixely default icons (see picture).

So, I was going to try to fix Papirus so that it worked correctly with MintInstall. The only problem is, I don't know where MintInstall is pulling these category icons from. I was hoping someone could help me. Where should the icons be located, and what should they be called, so that MintInstall can find them?

**Comment by Odyseus** [comment]
Hello, @AugustZellmer.

No picture can be seen. You can just drag and drop a picture file into the comment box and it will be "uploaded" and "presented" ready to be published.

Look at the file **/usr/lib/linuxmint/mintinstall/mintinstall.py** between lines 1150-1230. There are assigned all icons by name for the categories and sub categories.

**Comment by AugustZellmer** [comment]
Hm... I'll look into that. Thanks!

**Comment by AugustZellmer** [comment]
To follow up, I couldn't figure out how to fix it. But the lead dev of Papirus was super nice and fixed it for me.

This is how it looks now. The top-left icon still isn't using Papirus, but maybe you did that on purpose, I dunno.

Thanks for the help!

![newicons](https://cloud.githubusercontent.com/assets/1058866/21958706/21f93af4-da7a-11e6-8425-149075ed4123.png)
