### ISSUE TITLE
Remove hardcoding of Featured icon

### ISSUE THREAD

**Issue by theel0ja** [linuxmint/mintinstall#117]
Remove hardcoding of that Featured icon.

https://github.com/numixproject/numix-core/issues/3596

![image](https://cloud.githubusercontent.com/assets/5832930/23092909/ae6419d6-f5dd-11e6-8f82-88c9de19e80e.png)

**Comment by bil-elmoussaoui** [comment]
Here's the exact line of code, i can create a PR to fix this if you guys wish ;)
https://github.com/linuxmint/mintinstall/blob/a43cd5498598ae008557d70fb51999b6e4657eca/usr/lib/linuxmint/mintinstall/mintinstall.py#L1157
