### ISSUE TITLE
Summary text not readable on dark themes (font color problem)

### ISSUE THREAD

**Issue by vlad3-3-3** [linuxmint/mintinstall#119]
![software manager screenshot - dark theme](https://cloud.githubusercontent.com/assets/25938184/23184852/035e9700-f88a-11e6-8f9d-3962c3282967.png)

The summary and review text is not readable when the app is used with dark background themes (Linux Mint / Cinnamon). I think it has something to do with <fill="#555555">. Have a nice day!

**Comment by jessedubord** [comment]
Can confirm this bug is present in Mint 18.1, Cinnamon 3.2.7, Mint Y theme (dark) 1.1.5.

**Comment by Mystard** [comment]
Same with 18.1 XFCE...
Did a temp fix by editing line 1420 in /usr/lib/linuxmint/mintinstall/mintinstall.py
Just change the #555555 to something lighter. #969696 works great for me. The "x number of reviews" text is not visible either, that can be changed on line 1435.

**Comment by JosephMcc** [comment]
No longer an issue in git master.
