### ISSUE TITLE
Titlebar uses nonexistent icon

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintinstall#120]
I'm using one of the color variations of the Mint-X icon theme.  The title bar of the Software Manager window has a red circle-slash icon meaning "icon not found," although the global Apps menu and the window-list applet in the Panel have a suitable icon for this app.  

LMDE 2 Betsy, Cinnamon.  `mintinstall` version 7.7.5.

**Comment by JosephMcc** [comment]
What theme are you using for your window borders? Just so I have something to test against.

**Comment by JosephMcc** [comment]
Closing do to lack of response.
