### ISSUE TITLE
Splash screen suggestion

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintinstall#121]
Currently (`mintinstall` 7.7.5) this application has no splash screen.  Apparently (#40) it used to.  

This application takes noticeably longer to start than almost all other applications on the same computer.  (This is understandable, since `mintinstall` has to process data on tens of thousands of packages on startup.)  A splash screen would be appropriate, I think.  

The developers may already be thinking about this, since if I run `mintinstall` from a terminal, some profiling times are printed to the terminal window.

**Comment by CottonEaster** [comment]
I second this. If the program's launch cannot be accelerated, then at least the user should know that something's happening. I use a dualcore system with a SSD and lots of RAM. I dread to think how long the Software Manager would take to start on an (even) older processor, with a mechanical drive, and, say, fewer than 4GB of RAM.

**Comment by JosephMcc** [comment]
In git master startup of the application is now much faster. It sort of kills the need for this.

**Comment by CottonEaster** [comment]
> In git master startup of the application is now much faster to startup. It sort of kills the need for this.

Good! I look forward to the change being made available through an update.

**Comment by JosephMcc** [comment]
It won't be an update. It will come with Mint18.3 unless you want to build it yourself.
