### ISSUE TITLE
Wishlist option

### ISSUE THREAD

**Issue by guitarrist** [linuxmint/mintinstall#136]
It would be interesting an option to save an application to a list, then it could be downloaded in the future.
Similar to Android Play Store.

**Comment by RavetcoFX** [comment]
Don't wishlists make more sense if there are paid apps? I don't know if it makes as much sense here.

**Comment by guitarrist** [comment]
Not necessarily @RavetcoFX.
The user may not want to download at first because of lack of time, or he may be on a slow connection.

(or else) Imagine this other scenario: User is looking for a software that has a certain functionality. 
He will do the search, add everything he finds to wishlist, then he will download one at a time and remove from list.

Finally, if wishlists did not make sense to free apps, Google Play would not allow add to wishlist if app it is free.

**Comment by xenopeek** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow for feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
