### ISSUE TITLE
Add option for installing desktop/menu icon for flatpak apps

### ISSUE THREAD

**Issue by Schallaven** [linuxmint/mintinstall#153]
Hello!

Would it be possible to add buttons for adding desktop and/or menu icons for Flatpak apps? Or maybe add them automatically?

Right now, some users report that they don't know how to start applications except from software manager.

Also, could there be a "installed" category in the Flatpaks section in software manager to easily find and remove flatpaks?

Thanks!

**Comment by JosephMcc** [comment]
You don't say what desktop you are using, but under Cinnamon it seems to sometimes take a log out and log in for it to show up in the menu. Are there particular apps you are seeing issues with?

**Comment by Schallaven** [comment]
Sorry Joseph, was late when I was typing it (just did not want to forget):

_I_ did not try 18.3 Beta and the new software manager, yet; we just got some reports/comments (mainly in #linuxmint-chat) that flatpak apps don't show up in the Menu (all of them in Cinnamon, as far as I know/saw) and I thought I forward them here :) Ok, so this is the standard logout/login-thing then. Should have thought of this.

Other comments/reports were about "where can I see what flatpaks I have installed?". Of course you can use "flatpak list" and then remove it with it - but maybe adding a small category "installed" in the flatpak window is better? Maybe this of some sort already exists, but then it is not obvious (enough) to users.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintinstall/commit/c8f9b7a893d8deb05d7ff157cf6c03c0c92870cf
