### ISSUE TITLE
Add support for debconf dialogs

### ISSUE THREAD

**Issue by AsciiWolf** [linuxmint/mintinstall#156]
Please, consider adding support for debconf dialogs to mintinstall. For example the Steam package uses debconf to show the license agreements and fails to install when installed using mintinstall on the latest Linux Mint 18.3 beta.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintinstall/commit/623b4212c82d6b5835c1b87007ad98b3dedca3e4
