### ISSUE TITLE
flatpak software versions

### ISSUE THREAD

**Issue by Chocobo-ts** [linuxmint/mintinstall#165]
At the moment, mintinstall does not show the version of the proposed flatpak packages, only the branch (stable) without details

It will be great, if this info shown, how it implemented  for native deb-packages
Thanks!

**Comment by al-mission-2016** [comment]
In general, it would be convenient (at least for advanced users) to have following Flatpak info:
- app version (as was said above by Chocobo-ts)
- download size
- installed size (!!!)
- dependencies (maybe)

i.e. same as in Synaptic Package Manager.

Thank you LM team for your excellent work.

**Comment by xenopeek** [comment]
This requires flatpak version 0.10.1 or newer. That introduced the remote-info command http://docs.flatpak.org/en/latest/command-reference.html#flatpak-remote-info. Without remote-info there only is the remote-ls command, which can only show the flatpak names.

Linux Mint 19 (Ubuntu 18.04) will have the required flatpak version. LMDE 3 (Debian 9) doesn't.

**Comment by clefebvre** [comment]
We can probably backport flatpak 0.10.1 to LMDE 3.

**Comment by mtwebster** [comment]
Version, sizes, dependencies are shown in the latest mintinstall.  I'll have to test on LMDE when I get an iso to try.

**Comment by RoyiAvital** [comment]
Any chance having option to limit search of new program to FlatPak only?

**Comment by RoyiAvital** [comment]
@JosephMcc ,
What about the update process?
Currently it is done behind the scene without the ability of the user to control it.
Could it be integrated into the Software Manager?
Could I be able to see what's the version installed and what's the version to be updated to?

**Comment by mtwebster** [comment]
There's api now for our update manager to list and apply flatpak updates, but it hasn't been implemented in mintupdate yet

**Comment by RoyiAvital** [comment]
@mtwebster ,
Will it be part of Mint 19.0?
Will it be available at some point at 18.3?

Thank You.

**Comment by RoyiAvital** [comment]
@clefebvre ,
Any chance saying if this coming to 18.3?
