### ISSUE TITLE
Make review text copyable

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintinstall#166]
As a feature request, would it be possible to serve the Software Manager reviews as text so that they can be selected and copied.

The reason I ask this is that the first and second reviews for Google Earth, at time of posting, are very negative but written in German and a Slavic language respectively. I would have liked to copy that text to Google Translate in order to see what the reviewers' complaints about the software are, but am unable to do so.

**Comment by xenopeek** [comment]
Thanks for your contribution. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

For now you can copy such text by clicking on the "Click [here](https://community.linuxmint.com/software/view/googleearth) to add your own review" link that you'll find after the end of the reviews list.
