### ISSUE TITLE
Disable root nanny mode

### ISSUE THREAD

**Issue by mperkel** [linuxmint/mintinstall#167]
Really would not have to edit out the code that makes this program run as root. This is Linux and don't need root nanny PC mode installed. If someone has chosen to run without training wheels then you should respect that. Besides, the program has to be root in order to work so this makes no sense.

**Comment by JosephMcc** [comment]
Allowing installation of applications without asking for your password is just a bad idea.

**Comment by mperkel** [comment]
I can type apt install <app> without a password and it does the same thing. I live alone and it's not like people are coming by breaking into my house trying to install apps on my computer and are stopped because they don't have a password. If I'm already root I would have had to already authenticate.
