### ISSUE TITLE
flatpak error in mintinstall

### ISSUE THREAD

**Issue by rebelxt** [linuxmint/mintinstall#169]
I upgraded from Mint Mate 18.2 to 18.3. When attempting to install the flatpak version of VLC, the process continued until it tried to install additional dependencies. After a few seconds, it stopped, and VLC was not installed. 

Running mintinstall from a terminal shows:

> Detected system architecture: 'x86_64' (using 'x86_64')
load_cache took 334.363 ms
add_categories took 5.303 ms
build_matched_packages took 0.189 ms
add_packages took 1595.552 ms
process_matching_packages took 1.612 ms
add_reviews took 837.844 ms
Downloading new reviews
update_reviews took 1232.556 ms
add_flatpaks took 2838.617 ms
__init__ took 3261.616 ms
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1315, in add_flatpaks_async
    self.sync_flatpak_appstream()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1352, in sync_flatpak_appstream
    self.sync_flatpaks_into_appstream(remote_name)
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 59, in wrapper
    res = func(*arg)
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1308, in sync_flatpaks_into_appstream
    self.flatpak_installation.update_appstream_sync(remote_name, self.arch, False)
Error: g-io-error-quark: While pulling appstream/x86_64 from remote flathub: opcode open-splice-and-close: opcode open-splice-and-close: fsetxattr(user.ostreemeta): Operation not supported (15)

I cannot install any flatpak app. This does not happen on a clean installation of Mint Mate 18.3 in VirtualBox. If it matters, this particular installation of Mint Mate has been regularly upgraded from Mint 17.

I considered an uninstall/reinstall of flatpak, but apt-get wanted to remove:
  flatpak mint-meta-core mint-meta-mate mintinstall

That didn't seem to be a good idea.

**Comment by xenopeek** [comment]
Please troubleshoot and find the exact cause of the problem. You can reopen the issue if the responsible component proves to be Software Manager. If you need help with troubleshooting you can use the forums at https://forums.linuxmint.com/viewforum.php?f=47. For more information on our workflow and troubleshooting, read http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.
