### ISSUE TITLE
[RFE] Provide Linux Mint GTK themes on Flathub

### ISSUE THREAD

**Issue by AsciiWolf** [linuxmint/mintinstall#170]
Consider providing the Linux Mint GTK themes on [Flathub](https://flathub.org) so they can be used in Flatpak applications from Flathub. There are already [many themes](https://github.com/flathub?q=theme) available on Flathub and adding a new one is not an issue.

**Comment by JosephMcc** [comment]
We hope to. They currently aren't up to date for gtk3.22 though. I'm in the process of working on them so hopefully we'll be able to do that.

**Comment by JosephMcc** [comment]
We plan to try this at some point once the themes are actually ready.
