### ISSUE TITLE
[Feature request] Add tab with installed apps in Software manager

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mintinstall#171]
Default software manager Linux mint should have the tab with installed apps.
I am confident that it would be comfortable for users who want remove an application which name forget.

**Comment by xenopeek** [comment]
Would this be different from the "Show installed applications" option in the hamburger menu?

![Screenshot](https://i.imgur.com/proUhwg.png)

**Comment by xenopeek** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
