### ISSUE TITLE
Restored packages does not appears in "Installed applications" tab

### ISSUE THREAD

**Issue by snakebiter** [linuxmint/mintinstall#172]
Hi. I backed up list of installed software using Mint Backup Tool. Next I reinstalled system and restored packages with the same tool. Packages form list was installed correctly but they does not appears in mintinstall's "Installed applications" tab. Now I can't backup full list of installed packages for further restore actions.

Version: 7.8.9

**Comment by milangfx** [comment]
I think the issue is that the "Installed applications" category only shows packages that you installed with mintinstall. Since you installed / restored the packages with the Backup tool, they are not visible in mintinstall. 
Actually the "Installed applications" category is completely empty for me and I've never used the Backup tool. I guess it's because I usually install with _apt_.

**Comment by calexil** [comment]
is this getting fixed before mint 19 drops, I kinda need to have a backup of my programs

**Comment by smurphos** [comment]
`dpkg --get-selections > packages.list` in the terminal to get a list of all installed packages that you can use as input in Backup Manager after a fresh install of 19.

**Comment by snacaman** [comment]
`dpkg --get-selections > packages.list` contains all installed packages: by system installer, dependencies, etc. There is a risk that the list will contain system packages not present in newer mint version. Of course we can use console tools but this is not solution but poor workaround. Here, we are talking about mint backup tool and mintinstall. We want to use provided GUI tools in this case.

**Comment by smurphos** [comment]
The backup tool will deal with those issues reasonably gracefully, albeit with some user oversight. The Mint 19 backup function for installed apps is broken right now in any case as it's not listing even Software Manager installed packages as candidates for backup - see https://github.com/linuxmint/mintbackup/issues/55

As an alternative and reliable GUI option I use and recommend aptik-gtk - PPA link https://launchpad.net/~teejee2008/+archive/ubuntu/ppa

It can backup and intelligently restore user installed package lists from all install methods, additional repos / ppas, dconf, user crontabs, custom fstab entries etc etc.....

**Comment by snacaman** [comment]
Aptik is doing the same as `dpkg --get-selections > packages.list`. No offence friend but please do not off topic posts. We don't ask for alternatives in this discussion.

**Comment by smurphos** [comment]
@snacaman No it's not. Only trying to help.
