### ISSUE TITLE
Program shows as both installed and uninstalled

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintinstall#173]
![korganiser reported as installed](https://user-images.githubusercontent.com/9998846/34505972-b95896bc-f020-11e7-94e7-c90798ab363c.png)

But, when I click on the Korganizer icon . .

![one click later](https://user-images.githubusercontent.com/9998846/34505976-c2acd106-f020-11e7-95d3-b98fdfc74a9e.png)

**Comment by xenopeek** [comment]
There isn't a green checkmark in the first screenshot on Korganizer. That's strange. Do you in fact have Korganizer installed? Please share the output of command: `apt policy korganizer`

**Comment by JosephMcc** [comment]
Did you by chance install and then uninstall it? Just wondering if something didn't update properly.

**Comment by CottonEaster** [comment]
> Do you in fact have Korganizer installed? Please share the output of command: apt policy korganizer

I do not - not any more, anyhow. I gave up on all this calendar stuff. `apt policy korganizer` produces: 'Installed: (none)'.

> Did you by chance install and then uninstall it? Just wondering if something didn't update properly.

I do not recall, I am afraid - it was some time ago now.

**Comment by JosephMcc** [comment]
Is it still showing as installed in the software manager?

**Comment by CottonEaster** [comment]
No, neither when found through search nor when the search result is clicked upon.

**Comment by JosephMcc** [comment]
Ok. There isn't really anything for us to go on at this point then :)
