### ISSUE TITLE
mintinstall 7.8.9 I can not install programs !

### ISSUE THREAD

**Issue by ramzydoni** [linuxmint/mintinstall#175]
hey thanks to the developers for their efforts
I'm a beginner in Linux
I use Linux Mint 18.2 I worked to update to 18.3 and got a download manager problem I can not install the software inside
You tried to delete it sudo apt-get purge mintinstall
And then installed it did not fix the problem I wish help and thank you
https://i.imgur.com/TJRRTHH.png
https://i.imgur.com/ZjiDno1.png
https://i.imgur.com/NtCVBq3.png

**Comment by xenopeek** [comment]
Please use the forums for support with troubleshooting this: https://forums.linuxmint.com/viewforum.php?f=47
