### ISSUE TITLE
Flatpak: order of packs seems random and appears unchangeable

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintinstall#177]
So far as I can tell, there's no order, or control over the order, in which the 'packs' appear. More: the 'flathub' button, together with the fact that it is unclear what categories the search box searches (all applications? just flatpacks? just, er, packs from flathub?) makes finding applications confusing.

If we add in the fact that [I wasn't sure whether I'd managed to install a pack](https://github.com/linuxmint/mintinstall/issues/169), and that some programs have pack versions and normal version, then confusion abounds. (Did I install the package? Did I not? Which package did I install?) Or so it seems to me.

MintInstall 7.8.9.

**Comment by clefebvre** [comment]
Flatpaks are ordered by popularity, just like the other apps.
