### ISSUE TITLE
Support for flatpakref from other developers

### ISSUE THREAD

**Issue by Lvaskz** [linuxmint/mintinstall#178]
Some developers offer flatpakref files such as monodevelop and Linphone, and these are not stored in the flathub. Some unofficial developers also offer flatpakref, mintinstall could support these files for installation in gnome software style.

**Comment by mtwebster** [comment]
Supported in upcoming release.  You can 'launch' a flatpakref file from your file manager, or have your browser launch it as a handler when opening a link to one.
