### ISSUE TITLE
Flatpak Update option

### ISSUE THREAD

**Issue by Lvaskz** [linuxmint/mintinstall#179]
Actually mintinstall has not option to update some flatpak App. When some actualization is ready,  update option should appear, or some notification.

**Comment by xenopeek** [comment]
Flatpaks are updated automatically in the background, after you login.

**Comment by Lvaskz** [comment]
Hi, can you explain me how? you tell me about login. That means i must to close session on the desktop? I know there are things i must to know, but i am new in this, show me how.

thanks

**Comment by xenopeek** [comment]
See info here https://forums.linuxmint.com/viewtopic.php?f=47&t=260872#p1409486. For further support questions please use the forums.
