### ISSUE TITLE
Merging double entries?

### ISSUE THREAD

**Issue by orschiro** [linuxmint/mintinstall#180]
Redshift shows up twice. Not sure if it is the only application that does so. One entry comes from the package `redshift`. The other from `redshift-gtk`. How should we deal with this one?

It would definitely be more helpful to have one entry only that contains all reviews from people in one view.

![image](https://user-images.githubusercontent.com/170947/34907499-cf47f546-f87f-11e7-8138-64c7d5a1ffcf.png)

**Comment by xenopeek** [comment]
Strange. Please run `apt version mintinstall` on the terminal and share what version it says you have installed.

Here is how it looks for me on 7.8.8 on Linux Mint 18.3 Cinnamon. redshift-gtk is clearly named.
![Screenshot](https://i.imgur.com/s4J2uUW.png)

Did you search for redshift or how did you get to where you took the screenshot from? Can you try to reproduce it.

**Comment by orschiro** [comment]
> Did you search for redshift or how did you get to where you took the screenshot from? Can you try to reproduce it.

Correct. Just typed in `Redshift`. Currently not with Linux Mint. Can anyone else try to reproduce?

Otherwise, we can close it.

**Comment by xenopeek** [comment]
As I already tried to reproduce it with latest mintinstall version, closing this for now.
