### ISSUE TITLE
Adding a donate button to software view?

### ISSUE THREAD

**Issue by orschiro** [linuxmint/mintinstall#181]
Some open source projects could heavily benefit from more donations. Maybe more people would be willing to donate, they just don't even know that this possibility exists. 

How about adding a donate button to the software view? Would this be feasible and useful?

![image](https://user-images.githubusercontent.com/170947/34907544-a36b73fc-f880-11e7-9aed-d77695034031.png)

**Comment by orschiro** [comment]
@xenopeek can you let me know why you closed it?

**Comment by xenopeek** [comment]
We're bug squashing right now, and changing the way requests are handled. For requests like these the issue doesn't need to remain open once the request is clear and understood, and doesn't require further information gathering. The eventual and possible implementation is separate.

**Comment by orschiro** [comment]
Understood, thanks!
