### ISSUE TITLE
Software Manager displays incorrect information

### ISSUE THREAD

**Issue by cardich** [linuxmint/mintinstall#182]
The new Software Manager (SM, LM 18.3 Cinnamon) displays incorrect information when one selects an application to install or remove, which is most noticeable in the "Details" section. For example, when one selects from the Categories Internet -> email -> Evolution (which is not installed) it correctly displays 51MB disk space required. When one presses the right arrow on the top left corner of the SM's window and then selects another application, e.g. Thunderbird (which is installed) it displays again 51MB disk space required (in the Details section), which is different from what is displayed when one reverses the selection order.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/mintinstall/commit/b797c286f60300e3b06f8f98dfb9ebabded482ae
