### ISSUE TITLE
Software manager issue with scrolling

### ISSUE THREAD

**Issue by cardich** [linuxmint/mintinstall#183]
The new SM (LM 18.3 Cinnamon) does not allow scrolling with the keyboard (key-down): When one opens a Category which has no submenu (e.g. Accessories or Fonts), pressing the down-key selects the item (places a box around the item without opening it). Repeated pressing of the down-key makes it reach the bottom, but then it does not scroll the window and the selection gets out of view. When the Category has a submenu, pressing the down key selects an item from the menu. There is no way to select an item from the applications list. Although one can use the mouse to scroll the window, this is quite painful as most application lists are lengthy.

**Comment by mtwebster** [comment]
This is fixed by https://github.com/linuxmint/mintinstall/commit/52387db6998f881c5d43bd924bb2c760510532c0

(will be in next release)
