### ISSUE TITLE
Risky Software Manager in 18.3 Cinnamon

### ISSUE THREAD

**Issue by happyniko** [linuxmint/mintinstall#185]
With the release of Mint 18.3 Cinnamon there's the risk of system crash in the new Software Manager!

When you want to remove packages in the Software Manager the **window is to small to see the dependencies!** You have to expand the dialogue view manually each time. For removing packages this is really bad, because you don't see the dependencies and especially the ones you should not remove! **In the Software Manager 18.2 and earlier the system based dependencies were marked red! In Mint 18.3 you can't easily differ between them which can be removed and them which destroy your system when removed.** 

Default view of the dialogue
![grafik](https://user-images.githubusercontent.com/34000003/36635541-c0e8d8c6-19ae-11e8-9db9-dff5497a941d.png)

Software manager window (manually) expanded
![grafik](https://user-images.githubusercontent.com/34000003/36635543-c84e1d56-19ae-11e8-9c12-d96a1177a434.png)
Expanded view of the dialogue - system based packages aren't marked red anymore!!!

AND PLEASE: **Bring back the short description for each package in the overview. This is no use for first-time users, when you have to click each time to get information about the package.**

**Comment by xenopeek** [comment]
Digging into the code this dialog is the AptConfirmDialog from aptdaemon.gtk3widgets ([docs](https://pythonhosted.org/aptdaemon/aptdaemon.gtk3widgets.html)) from the (AptDaemon)[https://pypi.python.org/pypi/aptdaemon] Python module. This would need to be patched in that module as AptConfirmDialog has no arguments to let the caller set window dimensions.

#129 is indirectly to blame for this as that changed mintinstall to use AptDaemon.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintinstall/commit/b797c286f60300e3b06f8f98dfb9ebabded482ae
