### ISSUE TITLE
feature request: Add support for snaps

### ISSUE THREAD

**Issue by Lvaskz** [linuxmint/mintinstall#193]
Many original developers provide their packages in snaps formats.
The number of packages updated in linuxmint would grow considerably and clearly, end users like me, would have the most current software offered by the author; let say; in real time.
In fact, it would not be wrong to consider introducing a support for appimage as well, since many application developers offer their packages in appimage. It would be great to be able to download the package offered by the original distributor in the agnostic format they provide (flatpak, snap, appimage)
However, at the moment I think that giving support to snaps is fine.
At the time, I knew that linuxmint was going to introduce this support as well.

**Comment by clefebvre** [comment]
This will be considered when snap supports multiple remotes. As it is now it's only useful for the Ubuntu Store and doesn't represent a global distribution solution like appimage and flatpak.

**Comment by Lvaskz** [comment]
Hi, I know that linuxmint 19, has in addition to mintinstall, has gnome software. I did tests, and added snapd and enabled gnome software with support for flatpaks and snap, and it works like a charm. I think you could enable snapd by default and use gnome software to offer snaps and flatpaks by default. I think this is the way in which you could provide both formats and in an easy way to install from the gnome software center.
Of course, that will make more confortable for beginnig users, zero complications with terminal.
Cool!!!

**Comment by rik-shaw** [comment]
I wonder if this could be re-considered? I understand that Mint don't plan on shipping snap, but IF a user installs snap it would be great if mintinstall would support it. Yes this may be work that is not core to Mint but it would benefit some users of software not available as flatpaks such as Mailspring. By itself it would not cause negatives for Mint users as snap would not be installed by default.
