### ISSUE TITLE
If an additional Flatpak runtime needs to be installed, mintinstall errors out

### ISSUE THREAD

**Issue by DougBeney** [linuxmint/mintinstall#196]
I'm on a fresh Mint XFCE install.

I opened mintinstall and tried navigating to Spotify. When I clicked on the app listing, I got this error:

```
could not locate runtime 'runtime/org.freedesktop.Platform/x86_64/1.6' in any registered remotes
```

So, instead of using mintinstall I downloaded the Flatpak ref from the Flathub website for Spotify and then ran `flatpak install com.spotify.Client.flatpakref` in a terminal.

The Flatpak CLI prompted me if I wanted to install the runtime, I choose yes, the runtime installed, and then Spotify installed.

Is this something that you feel could be implemented into mintinstall?

**Comment by JosephMcc** [comment]
Thank for the report. It seems something was broken by an upstream update. Hopefully we'll get a fix out soon.

**Comment by Toyonut** [comment]
I am getting this as well on a fresh install of Mint 19 Cinnamon. I could partly get around it by adding the Gnome SDK flatpak repo, `flatpak remote-add --if-not-exists gnome https://sdk.gnome.org/gnome.flatpakrepo` but the KDE dependencies are still problematic as I haven't been able to find the repo for the KDE SDKs. I also don't know it this is the best way to fix this.

**Comment by ADepic** [comment]
@Toyonut 
https://raw.githubusercontent.com/KDE/flatpak-kde-runtime/master/kderuntime.flatpakrepo

Thats the kderuntime thing.

HOwever I don't know the command to install it.
I tried this:
flatpak remote-add --if-not-exists kde https://raw.githubusercontent.com/KDE/flatpak-kde-runtime/master/kderuntime.flatpakrepo

And it doesn't work.

Also this thing happened 2 days after fresh install.

**Comment by ADepic** [comment]
Workaround:
1. Go to [flathub.org](flathub.org)
2. Browse for package
3. Scroll down to the bottom of the package info
4. Copy the first "Command Line Instruction"
5. Your flatpak application will be installed.

**Comment by Toyonut** [comment]
This is fixed for me as of the mint install updates yesterday. I removed the additional gnome flatpak repo and was able to install flatpaks as normal. KDE based flatpaks worked fine too.

**Comment by DougBeney** [comment]
Just got a chance to test it out on a fresh install. Issue is gone. 🎆 Gonna go ahead and close this issue.
