### ISSUE TITLE
Software Manager: mouse over the application displays its description

### ISSUE THREAD

**Issue by hudsonfas** [linuxmint/mintinstall#197]
A suggestion: 
it would be more interesting when you pause the mouse over the application, immediately appear its description as a tip (you do not need to click on the application to see its description).

example: pausing the mouse over the application "Sublime Text", would receive the following tip:

"A sophisticated text editor for code, markup and prose."

**Comment by xenopeek** [comment]
You mean in the list of Editors' Picks? The applications list when browsing categories or searching already has a line underneath with that description.

**Comment by icarter09** [comment]
@xenopeek I agree with you that the line underneath already contains what would probably be the same description in a hover effect.  I believe this ticket can be closed out.
