### ISSUE TITLE
Error messages are very hard to read, due to horizontal truncation

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintinstall#201]
I have DPI set to double and can supply further system information upon request.

![image](https://user-images.githubusercontent.com/9998846/42297847-331a482e-7ffa-11e8-8a8c-d5d180e22521.png)

**Comment by asegarra** [comment]
This is also happening to me if you install something from the software store and it asks you to install required dependencies. I am running at 1080p, default DPI.

**Comment by xenopeek** [comment]
In current version of mintinstall the details textbox expands with the size of the window so more lines are displayed and the window isn't that wide by default. This looks to have been fixed in some previous release.
