### ISSUE TITLE
Blurred desktop

### ISSUE THREAD

**Issue by EgonFrerich** [linuxmint/mintinstall#202]
I am using VirtualBox. VMs with linuxmint 17.3 and 18.1 are activ.

I want to install another VM with linuxmint 19.1 (xfce-Edition). I could install the Live-DVD. But when I start the Live-DVD the desktop is blurred.

This information may help:
egon@Epsil173 ~ $ inxi -G
Graphics:  Card: InnoTek Systemberatung VirtualBox Graphics Adapter
           Display Server: X.Org 1.17.1 drivers: vboxvideo (unloaded: fbdev,vesa)
           Resolution: 1536x760@60.0hz
           GLX Renderer: Gallium 0.4 on llvmpipe (LLVM 3.6, 256 bits)
           GLX Version: 3.0 Mesa 10.5.9

**Comment by xenopeek** [comment]
Known issue. Workaround is to from the VM's menu do Input > Keyboard > Insert Ctrl-Alt-Backspace and then login with username mint and blank password.
