### ISSUE TITLE
crash video 

### ISSUE THREAD

**Issue by Robi1234567890** [linuxmint/mintinstall#203]
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/installer/installer.py", line 481, in _task_finished
    del self.tasks[task.pkginfo.pkg_hash]
KeyError: 'apt:bleachbit'

and
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 2515]
[New LWP 2517]
[New LWP 2518]
[New LWP 2519]
[New LWP 2527]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `engrampa /home/robert/Pobrane/xflux64.tgz'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f34e201ba80 (LWP 2515))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 2515]
[New LWP 2517]
[New LWP 2518]
[New LWP 2519]
[New LWP 2527]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `engrampa /home/robert/Pobrane/xflux64.tgz'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f34e201ba80 (LWP 2515))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f34df3e4801 in __GI_abort () at abort.c:79
#2  0x00007f34df42d897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f34df55ab9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f34df43490a in malloc_printerr (str=str@entry=0x7f34df558d88 "free(): invalid pointer") at malloc.c:5350
#4  0x00007f34df43be1c in _int_free (have_lock=0, p=0x556bf8caa170, av=0x7f34df78fc40 <main_arena>) at malloc.c:4157
#5  __GI___libc_free (mem=0x556bf8caa180) at malloc.c:3124
#6  0x00007f34dffbc45d in g_list_foreach () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x0000556bf860a3a7 in ?? ()
#8  0x0000556bf861ff3e in ?? ()
#9  0x0000556bf85fd0b7 in ?? ()
#10 0x00007f34df3c5b97 in __libc_start_main (main=0x556bf85fcf00, argc=2, argv=0x7fff991fb4c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff991fb4b8) at ../csu/libc-start.c:310
#11 0x0000556bf85fd13a in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 2515]
[New LWP 2517]
[New LWP 2518]
[New LWP 2519]
[New LWP 2527]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `engrampa /home/robert/Pobrane/xflux64.tgz'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f34e201ba80 (LWP 2515))]

Thread 5 (Thread 0x7f34c5b52700 (LWP 2527)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f34e0005f2a in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f34dff934f1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f34dffe87a4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f34dffe7e05 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f34df79c6db in start_thread (arg=0x7f34c5b52700) at pthread_create.c:463
        pd = 0x7f34c5b52700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139864632010496, -5161985862229311247, 139864632007808, 0, 139864670496928, 139864916203600, 5059084305359945969, 5059037471052906737}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f34df4c588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7f34d588f700 (LWP 2519)):
#0  0x00007f34df4b8bf9 in __GI___poll (fds=0x556bf8d7f850, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f34dffc0439 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f34dffc054c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f34d78f136d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f34dffe7e05 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f34df79c6db in start_thread (arg=0x7f34d588f700) at pthread_create.c:463
        pd = 0x7f34d588f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139864897550080, -5161985862229311247, 139864897547392, 0, 93922223342992, 140735762376512, 5059048871342883057, 5059037471052906737}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f34df4c588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f34d6a5a700 (LWP 2518)):
#0  0x00007f34df4b8bf9 in __GI___poll (fds=0x556bf8bde0c0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f34dffc0439 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f34dffc07d2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f34e05ace76 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f34dffe7e05 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f34df79c6db in start_thread (arg=0x7f34d6a5a700) at pthread_create.c:463
        pd = 0x7f34d6a5a700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139864916207360, -5161985862229311247, 139864916204672, 0, 93922222476064, 140735762377776, 5059051453155098865, 5059037471052906737}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f34df4c588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f34d725b700 (LWP 2517)):
#0  0x00007f34df4b8bf9 in __GI___poll (fds=0x556bf8bcc700, nfds=2, timeout=100) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f34dffc0439 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f34dffc054c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f34dffc0591 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f34dffe7e05 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f34df79c6db in start_thread (arg=0x7f34d725b700) at pthread_create.c:463
        pd = 0x7f34d725b700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139864924600064, -5161985862229311247, 139864924597376, 0, 93922222476144, 140735762377392, 5059054753300594929, 5059037471052906737}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f34df4c588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f34e201ba80 (LWP 2515)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 0, 140735762379504, 0, 93922224787072, 139865075879237, 0, 93922223332176, 93922224725200, 139865072792601, 686425678725230576, 139865072792601, 93922224725344, 139865072792601, 686425678725230608, 139865072789788}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f34df3e4801 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {2568991060, 1, 139865072987829, 0, 0, 0, 0, 0, 139865073153543, 2, 140735762379600, 140735762379352, 93922226874288, 140735762379136, 140735762379120, 140735762379408}}, sa_flags = -1725976208, sa_restorer = 0x1000}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00007f34df42d897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f34df55ab9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
        ap = {{gp_offset = 24, fp_offset = 32767, overflow_arg_area = 0x7fff991fb2a0, reg_save_area = 0x7fff991fb230}}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
        on_2 = <optimized out>
        next = <optimized out>
        str = <optimized out>
        len = <optimized out>
        newp = <optimized out>
        iov = <optimized out>
        total = <optimized out>
        cnt = <optimized out>
        buf = <optimized out>
        wp = <optimized out>
        old = <optimized out>
        cnt = <optimized out>
        result = <optimized out>
#3  0x00007f34df43490a in malloc_printerr (str=str@entry=0x7f34df558d88 "free(): invalid pointer") at malloc.c:5350
No locals.
#4  0x00007f34df43be1c in _int_free (have_lock=0, p=0x556bf8caa170, av=0x7f34df78fc40 <main_arena>) at malloc.c:4157
        fb = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        fwd = <optimized out>
        size = <optimized out>
        nextchunk = <optimized out>
        bck = <optimized out>
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        tc_idx = <optimized out>
        idx = <optimized out>
        old = <optimized out>
        old2 = <optimized out>
        fail = <optimized out>
        ignore1 = <optimized out>
        ignore2 = <optimized out>
        ignore3 = <optimized out>
        ignore = <optimized out>
        __atg1_result = <optimized out>
        ret = <optimized out>
        ret = <optimized out>
        ret = <optimized out>
        ret = <optimized out>
        ignore1 = <optimized out>
        ignore2 = <optimized out>
        ignore3 = <optimized out>
        heap = <optimized out>
        ignore = <optimized out>
#5  __GI___libc_free (mem=0x556bf8caa180) at malloc.c:3124
        ar_ptr = 0x7f34df78fc40 <main_arena>
        p = 0x556bf8caa170
        hook = <optimized out>
        mem = 0x556bf8caa180
        ar_ptr = <optimized out>
        p = <optimized out>
        hook = <optimized out>
        __x = <optimized out>
        ar_ptr = <optimized out>
        p = <optimized out>
        hook = <optimized out>
        __x = <optimized out>
#6  0x00007f34dffbc45d in g_list_foreach () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x0000556bf860a3a7 in ?? ()
No symbol table info available.
#8  0x0000556bf861ff3e in ?? ()
No symbol table info available.
#9  0x0000556bf85fd0b7 in ?? ()
No symbol table info available.
#10 0x00007f34df3c5b97 in __libc_start_main (main=0x556bf85fcf00, argc=2, argv=0x7fff991fb4c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff991fb4b8) at ../csu/libc-start.c:310
        self = <optimized out>
        __self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 1336163853787709681, 93922216890640, 140735762379968, 0, 0, 5162184046920057073, 5059036951179804913}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7f34e1e3e733 <_dl_init+259>, 0x7f34e1e17878}, data = {prev = 0x0, cleanup = 0x0, canceltype = -505157837}}}
        not_first_call = <optimized out>
#11 0x0000556bf85fd13a in ?? ()
No symbol table info available.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f34df3e4801 in __GI_abort () at abort.c:79
#2  0x00007f34df42d897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f34df55ab9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f34df43490a in malloc_printerr (str=str@entry=0x7f34df558d88 "free(): invalid pointer") at malloc.c:5350
#4  0x00007f34df43be1c in _int_free (have_lock=0, p=0x556bf8caa170, av=0x7f34df78fc40 <main_arena>) at malloc.c:4157
#5  __GI___libc_free (mem=0x556bf8caa180) at malloc.c:3124
#6  0x00007f34dffbc45d in g_list_foreach () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x0000556bf860a3a7 in ?? ()
#8  0x0000556bf861ff3e in ?? ()
#9  0x0000556bf85fd0b7 in ?? ()
#10 0x00007f34df3c5b97 in __libc_start_main (main=0x556bf85fcf00, argc=2, argv=0x7fff991fb4c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff991fb4b8) at ../csu/libc-start.c:310
#11 0x0000556bf85fd13a in ?? ()

**Comment by icarter09** [comment]
@Robi1234567890 have you experienced this issue since creating this ticket?
