### ISSUE TITLE
librecad not available to install?

### ISSUE THREAD

**Issue by zcot** [linuxmint/mintinstall#204]
A discussion came up in IRC and a number of us were wondering about it.

Nobody could figure out why it wasn't available with mintinstall.

Varying the search term, and title/description, nobody could pull it. (2d, cad, and qcad wasn't available either)

It is available using any of the apt search/install methods.

And it is available on the mint/community/software web page, but none of us even know what that relates to.

Perhaps it doesn't make it into some priority list with trying to go through over 50,000 packages, of which 10's of thousands aren't going to be searched for there anyway?

Is there some "dig deeper, I'll wait" search method? or skip any caching to get a full search? re-cache on a specific category?

Obviously mintinstall is not meant to reinvent the wheel and be the most advanced software manager, well on that note, it's really great as it is anyway btw.

But curious about the answer.

**Comment by mtwebster** [comment]
Sorry about this - it was inadvertant.  There are an enormous number of packages out there, and we try to trim them down to useful 'user' packages as much as possibly.  This includes filtering out anything beginning with `lib` (which is usually a library.)

**Comment by zcot** [comment]
Ah! Right. So there it is! :+1:
