### ISSUE TITLE
[Request] Allow easier differentiation between Flatpaks and Packages via Details Label

### ISSUE THREAD

**Issue by feren** [linuxmint/mintinstall#205]
This is simply a request for a 'Flatpak' label under Details to be added for when the user is viewing a Flatpak package in Software Manager.

Why? Because, for instance with "OBS Studio", it's VERY HARD to find out whether it's a Flatpak or a Package before installing it, unless you're clever enough to realise that since it has a huge size and has dots in its package name, that it's then a Flatpak package and know the Flatpak Repo names for easier identification of Flatpaks.

All I'm asking for is for, under 'Details', for there to be a label that says "Flatpak" or "This is a Flatpak Package" for Flatpak packages viewed in Software Manager.

**Comment by PizzaLovingNerd** [comment]
I agree, I think the best way to do it similar to the way discover does it. Here's a screenshot:
![screenshot 2018-07-16 12 38 40](https://user-images.githubusercontent.com/13041099/42779444-526b2b22-88f5-11e8-8dbe-16280aba4622.png)

**Comment by feren** [comment]
...or heck make a coloured highlight label in either Details, the top, or on the bottom-right of the icon itself, where it says 'Flatpak' around the coloured highlight.

**Comment by mtwebster** [comment]
Addressed in new release.
