### ISSUE TITLE
Software size not reported correctly

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintinstall#207]
When i go from software to software in Software Manager 7.8.9 on Linux Mint 18.3, the size is incorrectly reported and never seems to change.

![glchess](https://user-images.githubusercontent.com/4412114/44302556-23df4480-a33c-11e8-8a4e-eac2e95b0d61.png)
![dreamchess](https://user-images.githubusercontent.com/4412114/44302557-23df4480-a33c-11e8-8dd8-3d2377f27317.png)
![pychess](https://user-images.githubusercontent.com/4412114/44302558-2477db00-a33c-11e8-8672-6ee56b4dc6b0.png)

**Comment by xenopeek** [comment]
I think this is a regression in Software Manager 7.8.9 as I can't reproduce it with 7.8.8 and I seem to recall this was fixed before. Indeed, see https://github.com/linuxmint/mintinstall/issues/168#issuecomment-361887394 where it was previously reported and fixed for Linux Mint 18.3.

It's not reproducible on Linux Mint 19.

**Comment by icarter09** [comment]
@xenopeek should this ticket be closed?
