### ISSUE TITLE
Failed to download package files

### ISSUE THREAD

**Issue by theking2** [linuxmint/mintinstall#209]
Installing is not possible the following errors are shown:

Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt0_4.0.0-1ubuntu8.3_amd64.deb 404  Not Found [IP: 91.189.88.162 80]

No options are displayed.

**Comment by xenopeek** [comment]
The Ubuntu 18.04 repositories (package base for your Linux Mint 19) have version 4.0.0-1ubuntu8.2 and 4.0.0-1ubuntu8.5 of the libvirt0 package. At the time you received that error your system's package index cache must have listed the 4.0.0-1ubuntu8.3 version while that was no longer available for download. In case of such errors refresh your package index cache (restart Software Manager, click Refresh in Update Manager).
