### ISSUE TITLE
Error installing Flatpack in MintInstall and cli

### ISSUE THREAD

**Issue by OmarNsy** [linuxmint/mintinstall#211]
When trying to install [Minitube](https://flathub.org/apps/details/org.tordini.flavio.Minitube) I'll get this error:

> While pulling runtime/org.kde.Platform/x86_64/5.9 from remote flathub: Error receiving data: Connection reset by peer

I tried Software Manager and CLI still getting same error

 ```
~$ inxi -S
System:    Host: onb-pav Kernel: 4.15.0-34-generic x86_64 bits: 64
           Desktop: Cinnamon 3.8.9  Distro: Linux Mint 19 Tara
```
```
~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
```
```
~$ flatpak remotes
Name    Options
flathub system
```
```
~$ flatpak install flathub org.tordini.flavio.Minitube
Required runtime for org.tordini.flavio.Minitube/x86_64/stable (org.kde.Platform/x86_64/5.9) is not installed, searching... 
Found in remote flathub, do you want to install it? [y/n]: Y
Installing: org.kde.Platform/x86_64/5.9 from flathub
[#########           ] Downloading: 81.9 MB/201.0 MB (4.3 MB/s)    
error: While pulling runtime/org.kde.Platform/x86_64/5.9 from remote flathub: Error receiving data: Connection reset by peer
```
```
~$ sudo flatpak install flathub runtime/org.kde.Platform/x86_64/5.9
Installing: org.kde.Platform/x86_64/5.9 from flathub
[########-           ] Downloading: 129.2 MB/348.9 MB (4.8 MB/s)   
error: While pulling runtime/org.kde.Platform/x86_64/5.9 from remote flathub: Error receiving data: Connection reset by peer
```
```
~$ flatpak install flathub org.kde.Platform/x86_64/5.9
Installing: org.kde.Platform/x86_64/5.9 from flathub
[#######             ] Downloading: 22.1 MB/72.3 MB (2.8 MB/s)     
error: While pulling runtime/org.kde.Platform/x86_64/5.9 from remote flathub: Error receiving data: Connection reset by peer
```
![software manager_004](https://user-images.githubusercontent.com/6824916/45722695-9cbfff00-bb7b-11e8-8154-3a075bb50036.png)
![software manager_005](https://user-images.githubusercontent.com/6824916/45722694-9c276880-bb7b-11e8-94b6-b86e6ceb1104.png)

Tried another Flatpack just to make sure  

![software manager_007](https://user-images.githubusercontent.com/6824916/45722693-9c276880-bb7b-11e8-8e75-381aa08c4011.png)
![software manager_008](https://user-images.githubusercontent.com/6824916/45722692-9c276880-bb7b-11e8-9a80-40b5e082149f.png)

**Comment by mtwebster** [comment]
Give it a bit and try again later - I've definitely had connectivity issues with flathub before.

**Comment by OmarNsy** [comment]
> Give it a bit and try again later - I've definitely had connectivity issues with flathub before.

I'm trying for 6 hours

**Comment by xenopeek** [comment]
I've seen this happen various times myself and seen it reported by others on the forums. It appears to be due to high load on flathub.org but should eventually resolve itself. Try again at another time with your `flatpak install flathub org.kde.Platform/x86_64/5.9` command to install the required runtime flatpak.
