### ISSUE TITLE
KeepassXC is broken in 18.3 because of outdated flatpak

### ISSUE THREAD

**Issue by Sl0vi** [linuxmint/mintinstall#212]
I installed the KeePassXC flatpak through the software manager, but I can no longer launch the application.

If I try to launch it from the terminal I get the error:

error: Unknown socket type ssh-auth, valid types are: x11, wayland, pulseaudio, session-bus, system-bus

I reported this problem on the KeePassXC flathub project:

https://github.com/flathub/org.keepassxc.KeePassXC/issues/25

Basically I was told that the version of flatpak in Linux Mint 18.3 is outdated and therefore the application won't run.

This is the first application that I've encountered that suddenly broke while using flatpak but since flatpak seems to be introducing new features that aren't in the version shipped with 18.3 who knows which applications will break in the future.

This makes using flatpaks risky and completely unreliable.

**Comment by xenopeek** [comment]
flatpak 1.0.3 is now available on Linux Mint 18.3. The same version as the PPA that was recommended on the linked issue. The update should be available for your system through Update Manager, or will be shortly (depending on your repository mirror). I assume this will fix the installation issue with the KeePassXC flatpak.

**Comment by Sl0vi** [comment]
I can confirm that this issue has been fixed.

I just installed the flatpak update on my system and KeepassXC launches correctly now.
