### ISSUE TITLE
Support AppImage

### ISSUE THREAD

**Issue by cadamsdev** [linuxmint/mintinstall#214]
Can we get it so you can search the store for app images? There's some software that's not available as a snap or flatpak but available as an app image so would be really nice to have these.

Here's an example. Plex media player isn't available for snap or flatpak but there's an app image for it. (There's a snap for plex server but that's a completely different thing)

[https://knapsu.eu/plex/](https://knapsu.eu/plex/)

**Comment by chadalen** [comment]
@xenopeek 
This is the central repo for all AppImages, sorry for the super delayed response...
[https://appimage.github.io/feed.json](https://appimage.github.io/feed.json)

**Comment by xenopeek** [comment]
That makes getting description, icon and screenshots easy. If an entry has links, that's mostly to a GitHub project's releases page but without linking to specific files or providing link to signing key to authenticate any downloaded files.

**Comment by mfreeman72** [comment]
I would love to see this feature in mintinstall also, as well as possibly being able to update these through mintupdate (similarly to how Gear Lever can manage AppImage updates, but integrated with the Linux Mint ecosystem, and with mintupdate's update notifications).

**Comment by DetachHead** [comment]
i've opened a new issue specifically to support updates for installed appimages at https://github.com/linuxmint/mintupdate/issues/998
