### ISSUE TITLE
Software Manager on Mint 19 doesn't show all packages

### ISSUE THREAD

**Issue by burtbick** [linuxmint/mintinstall#215]
I was chasing an issue with K3b not recognizing WAV files.  Someone on the Mint forum suggested searching in Synaptic for k3b.  

When I did Synaptic showed extra packages including libk3b7-extracodes that did NOT appear in Software Manager.  

I tried other combinations of searching k3b, libk3b and even libk3b7-extracodecs in Software manager and none of those searches showed up libk3b7-extracodecs.  Installing  libk3b7-extracodecs using Synaptic resolved the K3b WAV file issue.

In the Linux Mint 18.x Software Manager searching for k3b shows all of the k3b related packages including the libk3b* ones.  So this appears to be new behavior.

Is this a known issue?  Is there some filtering option that I haven't spotted in the UI?

**Comment by mtwebster** [comment]
Prior to mint 18.3, no filtering was done on the apt cache - *all* packages were listed, regardless of their name.

As of [this](https://github.com/linuxmint/mintinstall/commit/9f65fa022d2d2e1f6e7755667c72cb50b91eb4dd) commit, packages are filtered based on various naming criteria that is more or less consistently used in debian packages.  This was mainly for performance reasons, and to keep packages that ordinary users might never be interested in individually (such as *lib*raries) from appearing in the listings.

Unfortunately (and obviously) this is imperfect - there are some packages that get incorrectly filtered out.  We address them individually as they're discovered, until such time as some better method presents itself.  Unfortunately I've yet to figure anything out with this with apt.  With flatpaks, this isn't an issue, as all flatpak applications declare themselves a such, and need no filtering.

The current filtering is done here:
https://github.com/linuxmint/mintinstall/blob/master/usr/lib/linuxmint/mintinstall/installer/_apt.py#L53

I'll see about white-listing the packages you've mentioned.

**Comment by burtbick** [comment]
Thanks Michael,That explains it.  It would be great to get the libk3b packages to show up since others may try to use K3b to rip or burn Audio CDs and hit the same speed bump.


-------- Original Message --------
Subject: Re: [linuxmint/mintinstall] Software Manager on Mint 19 doesn't
show all packages (#215)
