### ISSUE TITLE
Clicking on Etcher package creates window exceeding screen width

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintinstall#225]
Clicking on the package listing for Etcher-electron (which I have installed from an external repository) in the Software Manager creates a very wide package information window which exceeds the screen width (1366x768). It looks as if the window is about 1760 pixels in width and that this is because the header description text (immediately below the package name at the top and above the star rating) is lengthy.

I've tried pasting an image snapshot in here but Github says it can't process the file.

This may also affect other packages so I'll update this issue if I come across similar issues.

Mint 19.1 MATE. mintinstall 7.9.7.

**Comment by xenopeek** [comment]
If you can still reproduce this, can you take another screenshot and upload it to an image hoster like https://imgur.com/ and share a link to the uploaded image here?

**Comment by ewangi** [comment]
Here you go:

https://imgur.com/a/9ybNQA1
