### ISSUE TITLE
"Show Installed Applications" exhibits unusual behaviour

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintinstall#227]
My Software Manager is showing only the same two packages as installed when I click on "Show installed applications", no matter if I close Software Manager and re-open it or refresh the list of packages.

In addition, I launched my VirtualBox copy of Linux Mint 19.1 and, in that, the "Show installed applications" is permanently greyed out.

Edit: So it transpires that the Gsetting _com.linuxmint.install.installed-apps_ only has the two packages in question on my system and is a blank array on my VM, with no discernible way of refreshing that setting to reflect the actual situation of the packages which are installed on the system.

Mint 19.1 MATE. mintinstall 7.9.7.

**Comment by xenopeek** [comment]
It's only showing packages installed _through_ mintinstall. I think a change is planned to make it show all manually installed packages, regardless of which package manager (like mintinstall, synaptic, apt and dpkg) was used to install them. That would be all packages installed on the system excluding the ones installed by the Linux Mint installer. (See https://github.com/linuxmint/mintinstall/pull/216, which will be reworked to also benefit mintbackup.)

**Comment by ewangi** [comment]
Noted. Personally, unless I'm misunderstanding this, I would suggest that a feature to show *all* installed applications which are recognised by the package manager, i.e. even those installed by the Mint installer, would be very useful. Mint may provide a new system with vlc, for example, but it would be nice to see this included in the list of installed packages. In essence, "Show installed applications" would display all applications that have a green tick in the Software Manager. If there would be a need/wish for "Show manually installed applications" (or "Show user-installed applications") then that would be a separate feature.
