### ISSUE TITLE
Unable to install any package

### ISSUE THREAD

**Issue by Senset** [linuxmint/mintinstall#228]
There is a console output:
Detected system architecture: 'x86_64' (using 'x86_64')
load_cache took 3671.695 ms
add_categories took 57.044 ms
build_matched_packages took 0.467 ms
add_packages took 7280.426 ms
process_matching_packages took 5.522 ms
add_reviews took 2280.222 ms
Downloading new reviews
__init__ took 14204.185 ms
update_reviews took 3633.246 ms
add_flatpaks took 10979.786 ms
Synced flathub
sync_flatpaks_into_appstream took 10099.782 ms
show_search_results took 497.199 ms
show_package took 680.831 ms
org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/defer/__init__.py", line 477, in _inline_callbacks
    result = gen.throw(result.type(result.value).with_traceback(result.traceback))
  File "/usr/lib/python3/dist-packages/aptdaemon/core.py", line 913, in _run
    yield self._check_auth()
  File "/usr/local/lib/python3.5/dist-packages/defer/__init__.py", line 477, in _inline_callbacks
    result = gen.throw(result.type(result.value).with_traceback(result.traceback))
  File "/usr/lib/python3/dist-packages/aptdaemon/core.py", line 965, in _check_auth
    authorized = yield self._check_alternative_auth()
  File "/usr/local/lib/python3.5/dist-packages/defer/__init__.py", line 477, in _inline_callbacks
    result = gen.throw(result.type(result.value).with_traceback(result.traceback))
TypeError: __init__() missing 1 required positional argument: 'action_id'

Mint version: Linux Mint 18.3 Sylvia

**Comment by xenopeek** [comment]
I hope you managed to solve this. Considering age of the issue and further troubleshooting that would be needed to find a cause (it looks like you pip installed some conflicting packages), closing this. If you or somebody else has the same symptoms now I suggest to make a new issue for that.
