### ISSUE TITLE
Feature - add real package name to short listing for some aliased packages

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintinstall#232]
It would add more information and allow the user to make more informed decisions if some of those packages which use aliases (currently https://github.com/linuxmint/mintinstall/blob/master/usr/lib/linuxmint/mintinstall/mintinstall.py#L61) were to include their real package name in their one-line short listing (i.e. the line generated by a search or produced by listing a category).

For example, the short listing for "Multimedia Codecs" would read "Multimedia Codecs (mint-meta-codecs)".

Naturally, this could look a bit silly for simple capitalisation changes, being more applicable where the display name is quite different from the package name, so I would suggest that the aliases data structure be expanded to include a boolean field that indicates whether the package should include the package name in brackets in its short listing.

To illustrate the above, "VLC" would still read "VLC", but "Skype" would read "Skype (skypeforlinux)" and "Steam" would read "Steam (steam-launcher)".

If it were decided that this modification wouldn't look good in the package title itself, then it could be added in some manner to the one-line package description beneath it.

**Comment by xenopeek** [comment]
Thanks for submitting your feature request for Software Manager. For more information on our workflow and feature requests, see https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
