### ISSUE TITLE
[BUG] Mintinstall can't be run from app chooser from flatpak.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mintinstall#236]
I installed GameHub from flatpak.
I runed It and clicked option to integrate GamHub with Steam.
Steam has been detected (Steam is install from flatpak too because normal steam client have a error [**from Software manager and steam site**].
For fun I clicked to "Software manager" (green link) but showed up a error:
![obraz](https://user-images.githubusercontent.com/23406555/51979271-ff5fca80-248c-11e9-9c9a-c4e7740dab92.png)
Can't find sub process "gnome-software".

It shouldn't be "### gnome-software" but "**mintinstall**" or something.

**Comment by clefebvre** [comment]
Hi @pyroxar that's an issue in gamehub itself then. It should be reported to them directly.
