### ISSUE TITLE
Maybe, in my mintinstall v. 7.9.7., missing banner with random images from apps

### ISSUE THREAD

**Issue by DorianB2017** [linuxmint/mintinstall#241]
Hello!
Perhaps, in my mintinstall, v. 7.9.7, the banner with random images in applications is missing. This happened when I upgraded from Linux Mint 19.0 to Linux Mint 19.1.
If this is not a bug, how do I solve it.
If this is a bug, please resolve it.

Thank for understanding and best regards,
Dorian B.
![Captură de ecran din 2019-03-10 13-20-57a](https://user-images.githubusercontent.com/30018486/54084518-4c5f7800-433a-11e9-8959-4c4c33597cdb.png)
![Old mintinstall](https://user-images.githubusercontent.com/30018486/54084622-add41680-433b-11e9-9516-3963e8dd700a.png)

**Comment by clefebvre** [comment]
Hi, it depends on your resolution. If you've enough screen estate the banner appears.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintinstall/commit/5e0b3b99a11d0ec38f24caa77abe1d4c014e7c3b

**Comment by DorianB2017** [comment]
Thanks for your reply, but in Linux Mint 19.0 and Linux Mint 19.1 is the same resolution: 1360px x 768px (16: 9).

**Comment by DorianB2017** [comment]
You closed the case too fast, not seeing exactly what it is about. Indeed, it is also my fault that I did not say the resolution of the monitor from the beginning.
Please re-open the issue / case.
Thank you.

**Comment by clefebvre** [comment]
Hi @DorianB2017, I linked the commit which made this change, it's a bug fix. It's not just a matter of fitting in the screen, your panel size also gets into consideration. 768px is very small and mintinstall, with this commit, adapts to that by not using the banner, which is an optional feature.

That commit was made after Mint 19, that's why you see the behaviour change between the two releases.

**Comment by clefebvre** [comment]
Using Mint-Y (the size also changes depending on the theme), I get an app height of 715px with the git master version. The default panel is 40px tall and can go all the way to 60px. With all the defaults that means we're already at 715+40=755px. If you use another theme or a taller panel, it no longer fits in 768px.

**Comment by clefebvre** [comment]
This is mintinstall in 1024x768 with a 40px panel.

![image](https://user-images.githubusercontent.com/1138515/54086118-f42a7500-433d-11e9-91e0-03f9bbf623dd.png)

**Comment by clefebvre** [comment]
It fits, but it's very close, if you change the panel height, the icon theme (like described in https://github.com/linuxmint/mintinstall/pull/219) of the GTK theme, it might not fit anymore.

**Comment by gm10** [comment]
@clefebvre see my comments on slack.

**Comment by DorianB2017** [comment]
It can slightly reduce the images from "Editors' pick" programs, and then the banner enters without any problems in the Software Manager window, as it was in Linux Mint 19.0.
In mintinstall (Software Manager), the visual impact does everything, that is, the banner. The banner may attract many new users of Linux Mint, especially since started to decline users polled on DistroWatch on Linux Mint.
So let your attitude if mintinstall return as before, as in Linux Mint Cinnamon 19.0. I wish it was like it was before.
There are many laptops and some monitors the resolution: 1360px X 768px.
Please lot to consider what I wrote here.

**Comment by gm10** [comment]
how old are you, 12? lmfao (regarding emoji and comment in other thread). some people...

**Comment by clefebvre** [comment]
I pushed a fix. If anything changes (theme, icon theme, panel size) this won't fit anymore. It's only a matter of time before we get another bug report asking us to remove the banner in 768px, and we'll then set the limit to 800px... ah well, it's only a detail one way or another. For now, it will show a banner in 768px.

Dorian, you're forgetting the title and spacing in your calculation. I showed a screenshot of what fits, it "barely" does fit. It needs 755px, which means it fits in 768px with the default themes and panel height.

**Comment by DorianB2017** [comment]
I did not forget the title. That's what it is. I took into account both the title and the bottom bar (panel) as shown in the last picture attached to the comment https://github.com/linuxmint/mintinstall/issues/241#issuecomment-471310583.
For compromise, you can reduce, little, the images of the programs from "Editors' pick".

A postscript. I was a computer graphician and know very well what it means pixels, dots per inch (dpi), etc.

**Comment by DorianB2017** [comment]
Thank you for https://github.com/linuxmint/mintinstall/commit/602053c4bd24a4b3fce2fa893f112189f788040b.
Thnk you, Clem!

With consideration,
Dorian B.
