### ISSUE TITLE
What if you add feature to Software Manager so you can install Android apps on Linux Mint OOTB?

### ISSUE THREAD

**Issue by setsunati** [linuxmint/mintinstall#243]
Check Anbox https://anbox.io/

Kind of like how Chrome OS allows you to Android apps on Chromebook.

**Comment by clefebvre** [comment]
Hi @setsunati.

> Anbox is currently only distributed as a snap as snaps makes the life for us developers pretty easy.

If the devs are only interested in Ubuntu users and they only support distributing their software via a commercial 3rd party there's no reason for us to invest any time looking into it.

**Comment by gm10** [comment]
That aside, I don't think something like this should be available OOTB. Anbox requires modifying the kernel, that's not something that should be done for every user just because a few might want to install android apps. Most of us use them on a phone. ;)

**Comment by clefebvre** [comment]
Note: Running Android apps OOTB is an interesting idea and we would support it, but as @gm10 said modifying the kernel is problematic and it wouldn't be done just to achieve that. If we were to support this feature we'd probably do it without kernel deviations from upstream and with an upstream project which includes our users in its scope.
