### ISSUE TITLE
[Feature Request] Support for appstream://*.desktop URI Open With

### ISSUE THREAD

**Issue by feren** [linuxmint/mintinstall#247]
This Feature Request is just what the title itself reads, the addition of support for using MintInstall as an application for opening appstream://*.desktop links with.
(e.g.: appstream://nomacs.desktop would open MintInstall directly to nomacs's details page)

That's all for the request, so I'll end the description here for now...

**Comment by xenopeek** [comment]
Thanks for submitting your feature request for Software Manager. For more information on our workflow and feature requests, see https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
