### ISSUE TITLE
[Request] Have the publisher name appear in Flatpak Details

### ISSUE THREAD

**Issue by feren** [linuxmint/mintinstall#251]
Pretty much what the title says: It would be great to know who published a Flatpak before installing it by looking under Details with a label saying 'Author (Author Name Here)'.

**Comment by xenopeek** [comment]
Thanks for submitting your feature request for Software Manager. For more information on our workflow and feature requests, see https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
