### ISSUE TITLE
No way to install in list view

### ISSUE THREAD

**Issue by Xornot** [linuxmint/mintinstall#26]
There should be a button to install a package in the list view without having to double click and view the description first. I'll be looking at the code to see if I can do it myself, but I'm a novice in Python.

**Comment by asakpke** [comment]
Any progress or future plans on this issue?

**Comment by clefebvre** [comment]
UI was revamped and navigation is much improved. The decision was taken to keep lists and categories very clean and light though, so installations/removals are still only triggered from within the app page.
