### ISSUE TITLE
[Question] "Show installed applications" export list

### ISSUE THREAD

**Issue by martinandersen3d** [linuxmint/mintinstall#264]
I assume there is a file with applications installed through the "Software Manager"?

**Where is this data stored? :D**

I like to backup "Show installed applications" list every time i log in.

How can I backup just this list?

Thanks ;-)

----
i do not want the fuuuulll apt or dpkg list, with all the dependecies ;-)

![image](https://user-images.githubusercontent.com/19984581/67242238-65deab80-f455-11e9-994c-867502345aea.png)

**Comment by martinandersen3d** [comment]
I wrote a temporary script in case anyone need. There is _probably a better way..?_ :D

backupToolExportInstalledprograms.sh
```
#!/bin/bash
 
backupToolOutputDir='/home/m/Documents/Backups'
targetOutputDir='/media/m/Data/Dropbox/Linux/Backups/BackupTool'
 
sleep 0.5
 
# Notification in top-right corner
notify-send "BACKUP - START: Installed Programs List"
 
sleep 0.5
#zenity --info --text="BACKUP: Installed Programs List"
 
# There needs to be a & sign at the end, to proceed after the program has been opened.
# This means that: Open the program(process) and continue script
# mintBackup is a program that comes with Mint, its called "Backup Tool" and can be found in the start menu. 
/usr/bin/mintBackup & 
sleep 0.5
xdotool key Right Down Down Return
sleep 0.3
xdotool key Tab Tab Tab Tab Return
sleep 1
 
cp -r $backupToolOutputDir $targetOutputDir
 
sleep 1
# Notification in top-right corner
notify-send "BACKUP - DONE: Installed Programs List"
 
exit
```

**Comment by mtwebster** [comment]
I'm not sure if you're using mint or not, if so, you can use mintbackup (Backup Tool in the menu) to save a listing of all installed packages - this should match what you see in mintinstall's list.

**Comment by clefebvre** [comment]
Programmatically, it's part of mint-common's cache, and there's a fallback (less accurate) gsettings key:

https://github.com/linuxmint/mintbackup/blob/master/usr/lib/linuxmint/mintbackup/mintbackup.py#L693

```
installed_packages = pkgcache.get_manually_installed_packages()
if not installed_packages:
    settings = Gio.Settings("com.linuxmint.install")
    installed_packages = settings.get_strv("installed-apps")

```
