### ISSUE TITLE
 Bug in mintinstall: FileNotFoundError _usr_lib_linuxmint_mintinstall_mintinstall.py.1000.crash

### ISSUE THREAD

**Issue by mathieuaubert** [linuxmint/mintinstall#271]
Hello
Sorry for my level in English.
I have the same problem.
I have Mint 19.3 Cinnamon, fresh install
And Mintinstall have a problem :
MintInstall: Detected system architecture: 'i686' Installer: User pkgcache is most recent, using it. Traceback (most recent call last): File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 580, in do_activate self.on_installer_ready() File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 894, in on_installer_ready self.sync_installed_apps() File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1156, in sync_installed_apps installed_packages = self.installer.cache.get_manually_installed_packages() File "/usr/lib/python3/dist-packages/mintcommon/installer/cache.py", line 307, in get_manually_installed_packages installed_packages_apt = self._get_manually_installed_debs() File "/usr/lib/python3/dist-packages/mintcommon/installer/cache.py", line 291, in _get_manually_installed_debs installer_log = gzip.open(installer_log, "r").read().decode('utf-8').splitlines() File "/usr/lib/python3.6/gzip.py", line 276, in read return self._buffer.read(size) File "/usr/lib/python3.6/gzip.py", line 482, in read raise EOFError("Compressed file ended before the " EOFError: Compressed file ended before the end-of-stream marker was reached Error in sys.excepthook: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f: FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/var/crash/_usr_lib_linuxmint_mintinstall_mintinstall.py.1000.crash'

I have test mint-common 2.0.7 (https://www.dropbox.com/s/gvk11yic5ukah3v/mint-common_2.0.7_all.deb?dl=0) and 2.0.9 but the problem persist (cf https://github.com/linuxmint/mintinstall/issues/263#issuecomment-572778003)

Thanks

**Comment by mtwebster** [comment]
linked the old bug from this commit :)

fixed by https://github.com/linuxmint/mintcommon/commit/c997fc7ff7f45817c67c3f110821a4e1114c22ea

I'm not sure what would cause an issue with the file it fails on (`/var/log/installer/initial-status.gz`), but it shouldn't kill mintinstall.

**Comment by mathieuaubert** [comment]
Thx, It's working, it's perfect
