### ISSUE TITLE
Show details of progress for Flatpak apps

### ISSUE THREAD

**Issue by apandada1** [linuxmint/mintinstall#273]
Mintinstall does show a progress bar, but does not show the amount downloaded and the speed of the download for flatpak apps. It would be nice to have this feature.
![Screenshot from 2020-03-19 10-32-02](https://user-images.githubusercontent.com/3063132/77033401-2a78e680-69cd-11ea-990d-112d2dc5e08a.png)

**Comment by xenopeek** [comment]
Thanks for submitting your feature request for the Software Manager. For more information on our workflow and feature requests, see https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
