### ISSUE TITLE
Add Lutris to Software Center

### ISSUE THREAD

**Issue by AsciiWolf** [linuxmint/mintinstall#279]
I am not sure if this is a good place to ask this, feel free to close this issue if it is not. Anyway, I think that it would be great for many Linux Mint users if [Lutris](https://lutris.net) was available directly from the Software Center.

**Comment by clefebvre** [comment]
Lutris needs to get into Debian first, that will make it become available in LMDE, Ubuntu and Linux Mint, and automatically then into the Software Manager.

Another way for it to get there would be to get into Flathub.
