### ISSUE TITLE
Mintinstall only showing installed applications

### ISSUE THREAD

**Issue by dm2912** [linuxmint/mintinstall#285]
Ok, this is driving me insane. 

Mint 20 (in place upgrade from 19.3)
Have tried a forced reinstall of mintinstall

If from the main menu i go into a category, for example in this instance "games", all it is offering me is apps that are already installed

![image](https://user-images.githubusercontent.com/25871666/87254827-846e5200-c47d-11ea-86e6-0acf3a4187ab.png)

Similarly, in education, all its offering me is apps that are already installed 

![image](https://user-images.githubusercontent.com/25871666/87254834-a071f380-c47d-11ea-940c-8b0fb64f56b8.png)

**Comment by dm2912** [comment]
ok, ive no idea how but somehow ive fixed it.

**Comment by mtwebster** [comment]
If it happens again, try:

```
sudo rm -rf ~/.cache/mintinstall
sudo rm -rf /var/cache/mintinstall
```
