### ISSUE TITLE
Install beta versions of software

### ISSUE THREAD

**Issue by ovari** [linuxmint/mintinstall#288]
Please advise how to install the beta version of software using the `Software Manager`.

Thank you

> In KDE Discover when I chose Thunderbird flatpak then I can switch between flathub and flathub-beta versions. I don't know about Mint store app though.
https://github.com/flathub/org.mozilla.Thunderbird/issues/120#issuecomment-660626523

**Comment by mtwebster** [comment]
You should be able to click any link to a .flatpakref file or launch it from a file manager to install from the software manager.  I believe you can also add remotes in the same manner to browse their apps.

**Comment by ovari** [comment]
Can flatpak-beta from flathub be able to be installed from Linux Mint's `Software Manager`?

**Comment by mtwebster** [comment]
https://flathub.org/beta-repo/flathub-beta.flatpakrepo

Click that and open with software manager

**Comment by ovari** [comment]
![image](https://user-images.githubusercontent.com/17465872/87887134-c131de80-ca65-11ea-9783-d0ab97a399ac.png)

**Comment by ovari** [comment]
Sorry, now it is showing. Just don't know why it wasn't showing before.

![image](https://user-images.githubusercontent.com/17465872/87887222-8c725700-ca66-11ea-8bee-186d25b05a5b.png)

**Comment by ovari** [comment]
Another error message.

![image](https://user-images.githubusercontent.com/17465872/87887364-c42dce80-ca67-11ea-89ac-09ee553d1b13.png)

**Comment by ovari** [comment]
Another error message.

![image](https://user-images.githubusercontent.com/17465872/87887370-e32c6080-ca67-11ea-9da9-8ebad19d136f.png)
