### ISSUE TITLE
Software Manager GUI improvement suggestion

### ISSUE THREAD

**Issue by noname-lols** [linuxmint/mintinstall#298]
Issue: When I'm in the software manager's "Installed programs"- if i click on an installed app in the list, and press back afterwards, it takes me back to the start of the list. In short, the list gets refreshed and I get sent back to the start which is frustrating. Small issue but I'd love for it to get improved so the experience is better.

**Comment by helioguardabaxo** [comment]
@noname-lols 
I'm using mintinstall 8.0.9 and its work correctly on Linux Mint 20.03.
