### ISSUE TITLE
A papercut: 'click here to add your own review' opens a seemingly irrelevant webpage

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintinstall#305]
Here is what I saw after clicking that button.

![image](https://user-images.githubusercontent.com/47056543/116811465-66bfc580-ab41-11eb-94a3-77d56a2f386e.png)

The page contains nothing about writing a review!

Perhaps I needed to be logged into the website. But a Linux distribution that means to be user- and indeed beginner-friendly should make that clear. Here we have one possible reason that your site contains few reviews.

**Comment by mtwebster** [comment]
If your scroll wheel is broken I imagine this could be a problem, but otherwise I don't see this as an issue - the reviews are there if you scroll down.

That's a flatpak - that's the reason there aren't a lot of reviews - not many people use (or are willing to use) flatpaks yet.
