### ISSUE TITLE
Add manual build instructions

### ISSUE THREAD

**Issue by Diacius** [linuxmint/mintinstall#308]
If people want to use mintinstall with a different distro (like me, i hate gnome software and kde discover), or want to build manually for Mint, could there be build instructions like the ones for [linuxmint/sticky](https://github.com/linuxmint/sticky)?

**Comment by m8** [comment]
You're right, I added in #310 .

**Comment by Diacius** [comment]
Thanks for the info, but it doesn't help on non mint distros due to special packages, I'll close this since mint isn't responsible for other distros
