### ISSUE TITLE
Show 'open' button on installed applications.

### ISSUE THREAD

**Issue by alextpedro** [linuxmint/mintinstall#313]
When you install something through the software manager it changes the install button to a 'remove' button, but doesn't give the user a way to open the application from that window. I suggest a new button should show up which launches the application. Something like what happens when you install an app through the play store on android.

**Comment by mtwebster** [comment]
Hi, is already the case as long as the software manager can figure out how to launch the program:
![image](https://user-images.githubusercontent.com/262776/125177463-e0aba500-e1a9-11eb-96f5-5b329f4b9064.png)

If a program wants to show up in the menu or elsewhere on the desktop, it provides a `.desktop` file which is installed with the package. If mintinstall finds that, it can launch the program. It tries a couple of other alternatives as well, but if it can't figure this out it hides the launch button.

What package did you install?

**Comment by alextpedro** [comment]
Spotify
