### ISSUE TITLE
Mintinstall doesn't mark dependencies properly

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintinstall#317]
When installing an apt package the dependency of the package that should be marked as auto-installed are marked as manually installed 
This make the package hard to remove and can't be remove without reading logs files.
Emacs when installed using the apt command will mark emacs-bin-common as automatic 
But when using mintinstall it was marked as manually installed 
Edit: 
System information
Linux mint 20.2 
Mintinstall 8.0.8

**Comment by xenopeek** [comment]
I checked and see the same difference between installing with apt and with mintinstall. Further, I also tried installing it with Synaptic and that also marks it as not manual installed (same as apt).

**Comment by NachosCheeseDip** [comment]
> I checked and see the same difference between installing with apt and with mintinstall. Further, I also tried installing it with Synaptic and that also marks it as not manual installed (same as apt).

Weird.. This issue only occur for me in mintinstall

**Comment by fredcw** [comment]
@xenopeek That's strange. For me, software manager is marking all dependencies as manual on both 20.2 (mate) and 20.2 (cinnamon daily builds) but not 19.3 cinnamon.

**Comment by fredcw** [comment]
I think I found the issue https://github.com/linuxmint/mintcommon/commit/125c19f07bb6b6bef8afa52563d24bb59ac4ea38

**Comment by mtwebster** [comment]
As of 8.2 Packagekit is now used for apt operations and only the target package is specified.
