### ISSUE TITLE
Flathub.org Https cert. dependency error

### ISSUE THREAD

**Issue by deatrys** [linuxmint/mintinstall#325]
I am trying to install Mint, and I have it almost working, but there's an issue with "mintinstall":

Setting up mintinstall (8.0.8) ...
error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: Unacceptable TLS certificate

It seems to require the flathub.org service to have an up-to-date cert, so it doesn't work

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintinstall/issues/326
