### ISSUE TITLE
[Feature Request] Warning Label when installing Flatpaks from mintinstall (Software  Store)

### ISSUE THREAD

**Issue by mystic-githuber** [linuxmint/mintinstall#330]
My concern with mintinstall is that, new users should have some sort of warning when installing Flatpak apps because most of them are packaged by random users and should prioritize deb packages over their counterparts in Flathub. I know they are sandboxed but so are Android apps from the Play Store and malware still gets through.

Very yew software like Firefox is directly packaged from the developer.

**Comment by clefebvre** [comment]
Very good point.

**Comment by haggen88** [comment]
For example ElementaryOS displays a warning in its software [center](https://user-images.githubusercontent.com/68134588/145692237-4ad5ed44-c5bc-42a3-ba28-38a7b8d164a8.png):
"Non-Curated:  Not reviewed by Elementary for security, privacy or system integration"

**Comment by xenopeek** [comment]
Flathub reviews app submissions, to meet their [app requirements](https://github.com/flathub/flathub/wiki/App-Requirements). And they are [working on](https://discourse.flathub.org/t/seeking-contractors-for-work-on-flathub-project/1889) adding first party verification (making it discoverable that the build configuration for an app is maintained by the app's developers).

Software [developed by Linux Mint](https://projects.linuxmint.com/projects.html) is obviously directly packaged from the developer but **most deb packages** from the package base repositories are in fact **not directly packaged from the developer**. Most are packaged by volunteers, not first party developers. Same as for flatpaks.

So I don't follow the distinction. While it may be useful to make it more clear a flatpak is being installed (and explain what it is, the pros and cons) I'm not clear on why you think a flatpak maintainer is less trustworthy than a deb package maintainer.

**Comment by mystic-githuber** [comment]
@xenopeek 

I though the distro (in this case ubuntu) packages them for us?

**Comment by xenopeek** [comment]
@mystic-githuber yes, apps in the Ubuntu package base are packaged by Ubuntu package maintainers. Not by the developers of those apps. The majority of packages in the Ubuntu package base are in the universe repository, for which Ubuntu community members and volunteers do the package maintenance. And most packages in the universe repository are imported from Debian, which is entirely operated by volunteer package maintainers. Nothing wrong with that but I simply don't see why you distrust volunteers packaging flatpaks but you don't have the same distrust for volunteers packaging debs. In most cases neither are developers of your apps.

**Comment by haggen88** [comment]
Flathub is preparing a verification system. Perhaps this badge system can be integrated into mintinstall in the future.

ref. https://debugpointnews.com/flathub-verification-kodi/

**Comment by haggen88** [comment]
The apps are already shown as verified on the new [flathub website](https://flathub.org/)

**Comment by mtwebster** [comment]
I had a look at it a week or so ago, I'm not going to do anything with this until it's no longer experimental and hopefully some  guidelines are provided. I want to be sure I'm even *allowed* to do this, as we're another tier in the distribution path - this is a flathub store thing, not flatpak.

From appstream.xml:
```
<custom><value key="flathub::verification::verified">true</value>
  <value key="flathub::verification::timestamp">1678267902</value>
  <value key="flathub::verification::method">website</value>
  <value key="flathub::verification::website">kodi.tv</value>
</custom>
```
