### ISSUE TITLE
feature request: search box looses focus

### ISSUE THREAD

**Issue by boxedy** [linuxmint/mintinstall#334]
when typing in the search box, as soon as any search results are returned the search box looses focus.

if the search results load too quickly (before finishing typing the query), usually the returned results are not helpful. in order to continue the search the search box need to be refocused.

is it possible to have the search box not loose focus when returning results?

**Comment by mtwebster** [comment]
What mintinstall  versions?

This should be fixed in 8.1.1:

https://github.com/linuxmint/mintinstall/commit/219a82317e2924bd48393eb25a87cf84200c3035
https://github.com/linuxmint/mintinstall/commit/f2ad7f426637d09b4d02e633d1746c9aa1111808
