### ISSUE TITLE
Two seperated string fo "reviews" in po file

### ISSUE THREAD

**Issue by mskf1383** [linuxmint/mintinstall#335]
In languages like Persian, we don't say "5 review**s**"; Only "5 review" (don't use plural form for that).
In mintinstall `.po` file, there is only one string for "reviews". But it used in two places in app. One at the bottom of stars in list view (That is like *5 reviews*, and must translate singular [in Presian]), And one other in apps full descriptions (Which is used as an title for all reviews, and must translate plural [in Persian]).
Please seperate it as two strings.
Thanks!

**Comment by mskf1383** [comment]
From Launchpad:
```
Located in usr/lib/linuxmint/mintinstall/mintinstall.py:417 usr/lib/linuxmint/mintinstall/mintinstall.py:2115 usr/lib/linuxmint/mintinstall/mintinstall.py:2146 usr/share/linuxmint/mintinstall/mintinstall.glade.h:17
```

**Comment by mtwebster** [comment]
It'll be a while before we load new translations onto Launchpad but this should allow you to handle review/reviews properly.

Thanks!
