### ISSUE TITLE
Software Manager/Mintinstall doesn't launch

### ISSUE THREAD

**Issue by fuadnse03** [linuxmint/mintinstall#337]
You will understand the problem I am facing if you watch the video
[https://drive.google.com/file/d/1JlMB6AFFQsMelnll4nXO7F25_9rz5Tsa/view?usp=sharing](url)

**Comment by fuadnse03** [comment]
attached mp4

**Comment by xenopeek** [comment]
For help with troubleshooting please use one of the support channels (forums, IRC, Discord, Reddit). If after troubleshooting the cause is found to be a bug in the code you can report it here.
