### ISSUE TITLE
Flatpak of Thunderbird fails to install

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintinstall#341]
**Describe the bug**

Initially, 1) the flatpak of Thunderbird fails to install, giving an error message. Subsequently 2) mintUpdate claims that the app has been installed but the 'launch' button does nothing (and one cannot launch from terminal, either - even if one installs the flatpak via terminal).

**Screenshots**

Re 1:
![image](https://user-images.githubusercontent.com/47056543/188772852-4c8d9f11-bc07-416a-9a3f-a3baa7f132ed.png)

**To Reproduce**
1. Open mintInstall.
2. Try to install the Thunderbird flatpak.
3. See error message.
4. Try again to install it. This time it will work (if your experience is like mine).
5. Click 'Launch' repeatedly.
6. See that nothing happens.

**Expected behavior**
It should install and then launch.

**Distribution:**
Linux Mint 21

**Software version:**
8.1.2

**Additional context**

```
$ flatpak list
Name                                  Application ID                           Version Branch Installation
[. . .]
GNOME Application Platform version 42 org.gnome.Platform                               42     system
Adwaita dark GTK theme                org.gtk.Gtk3theme.Adwaita-dark                   3.22   system
Mint-Y Gtk Theme                      org.gtk.Gtk3theme.Mint-Y                         3.22   system
Mint-Y-Dark Gtk Theme                 org.gtk.Gtk3theme.Mint-Y-Dark                    3.22   system
Mint-Y-Dark-Teal Gtk Theme            org.gtk.Gtk3theme.Mint-Y-Dark-Teal               3.22   system
Thunderbird                           org.mozilla.Thunderbird                  102.2.1 stable system
$ flatpak run org.mozilla.Thunderbird
error: runtime/org.freedesktop.Platform/x86_64/21.08 not installed
$ flatpak install  org.mozilla.Thunderbird
Looking for matches…
Required runtime for org.mozilla.Thunderbird/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub
Do you want to install it? [Y/n]: 
Info: (pinned) org.freedesktop.Platform.Icontheme.Paper//1.0 is end-of-life, with reason:
   The Icontheme extensions are not used anymore.

org.mozilla.Thunderbird permissions:
    ipc       network               cups                  pcsc                    pulseaudio       wayland      x11
    dri       file access [1]       dbus access [2]       bus ownership [3]

    [1] /run/.heim_org.h5l.kcm-socket, xdg-download, xdg-run/gnupg:ro, ~/.gnupg
    [2] org.a11y.Bus, org.freedesktop.Notifications
    [3] org.mozilla.thunderbird_default.*


        ID                                       Branch           Op           Remote           Download
 1. [/] org.freedesktop.Platform                 21.08            i            flathub            48.7 MB / 200.4 MB
 2. [ ] org.mozilla.Thunderbird.Locale           stable           i            flathub          < 40.4 MB (partial)
 3. [ ] org.mozilla.Thunderbird                  stable           i            flathub          < 81.0 MB

Installing 1/3… ████████████          60%  5.2 MB/s  00:06error: Failed to install org.freedesktop.Platform: While pulling runtime/org.freedesktop.Platform/x86_64/21.08 from remote flathub: Server returned status 503: Service Unavailable
```

The syslog has:

`libostree HTTP error from remote flathub for <https://dl.flathub.org/repo/objects/f4/4307a17336031ddd0ce1898b8645a0056e1ded95a82dcdba5c12dd6678e29a.dirtree>: Server returned status 503: Service Unavailable`

Cf. #260?

Note also that it is important that the Thunderbird flatpak work. For, the repository version of Thunderbird is significantly behind the current release of Thunderbird.

**Comment by mtwebster** [comment]
You may just need to wait a few hours or a day and try again - it looks like an issue with flathub. I've had it happen in the past once or twice.

**Comment by LinuxOnTheDesktop** [comment]
Understood, and thanks, but I think it is clear that mintInstall does not handle the problem gracefully. Problem 1 is one thing - though that message could be more readily intelligible - but problem 2 is pretty ugly.

**Comment by mtwebster** [comment]
Error handling should be improved in 8.2
