### ISSUE TITLE
Software manager does not open anymore :-(

### ISSUE THREAD

**Issue by madrbperu** [linuxmint/mintinstall#353]
Hello, I noticed this morning that my software manager does not want to open anymore, when I click on the menu link, the cursor spins for 30 seconds and goes back to the arrow pointer but no joy. I believe the last time I used it was about a week ago, although I do not use it very much since I install apps through terminal. Is there a way you can guide me and troubleshoot this? Please let me know if you need any reports so I can provide them for you, by the way, I don't recall doing anything out of the ordinary on this laptop because this is my work device and I don't mess with it, I have other PC's I usually grab and tinker about. I'll appreciate your prompt response. I almost forgot, this is what I have:

-Version-
Kernel		: Linux 5.4.0-135-generic (x86_64)
Version		: #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022
C Library		: GNU C Library / (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Distribution		: Linux Mint 20.3
-Current Session-
Computer Name		: manu-linuxmint1
User Name		: manu (Manuel del Rio)
Language		: LC_CTYPE=en_US.UTF-8;LC_NUMERIC=agr_PE;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=agr_PE;LC_MESSAGES=en_US.UTF-8;LC_PAPER=agr_PE;LC_NAME=agr_PE;LC_ADDRESS=agr_PE;LC_TELEPHONE=agr_PE;LC_MEASUREMENT=agr_PE;LC_IDENTIFICATION=agr_PE (en_US)
Home Directory		: /home/manu

Thank you.

**Comment by carlosmintfan** [comment]
Could you run `mintinstall` from the terminal?

**Comment by madrbperu** [comment]
Hi Carlos,

I can type it inside the terminal, but these are the results, and I believe it has something to do with Python...

***@***.***:~$ mintinstall
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 16, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 16, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'



Manuel A. del Río Bartra
Administrador de Servicios Web
Cel: 976-678-998

[https://n7lpeq.bn1301.livefilestore.com/y2pORGVpGmLJOHcMH123M9KoP3djZkXY5e5P044LqN8X35pUXVdW6T8dTxhOf9L3LczJ-zoeg38SPW4hZ5dz5TihzrVWzABvN8Kat2f1n_ZfK0/cara1.jpg?psid=1]
________________________________

**Comment by mtwebster** [comment]
Have you installed any python modules in some way other than using the system's package manager? (Maybe related to ssl)

It's generally not a good idea to modify the system's python installation. If you must use them you should set up a virtual python environment.

**Comment by madrbperu** [comment]
Hi Michael,

It's possible that I installed new modules with Python or pip commands, but it never occurred to me that doing so might have an impact on an operating system.

I have not installed system packages using any other method except through the automatic notification icon, not even using synaptic.

I have never forced upgrading or uninstalling python versions except through the automatic notification icon.

I still think it may be related to the system using the wrong version somehow, we are probably on python version 3.8 and the system is picking up a different one, hence the errors.

Any other ideas? I'll appreciate it



Manuel A. del Río Bartra
Administrador de Servicios Web
Cel: 976-678-998

[https://n7lpeq.bn1301.livefilestore.com/y2pORGVpGmLJOHcMH123M9KoP3djZkXY5e5P044LqN8X35pUXVdW6T8dTxhOf9L3LczJ-zoeg38SPW4hZ5dz5TihzrVWzABvN8Kat2f1n_ZfK0/cara1.jpg?psid=1]
________________________________

**Comment by mtwebster** [comment]
Try:
```
apt uninstall python3-openssl
```

**Comment by madrbperu** [comment]
Hi Michael,

There is no "apt uninstall python3-openssl" maybe "apt remove python3-openssl"?


Manuel A. del Río Bartra
Administrador de Servicios Web
Cel: 976-678-998

[https://n7lpeq.bn1301.livefilestore.com/y2pORGVpGmLJOHcMH123M9KoP3djZkXY5e5P044LqN8X35pUXVdW6T8dTxhOf9L3LczJ-zoeg38SPW4hZ5dz5TihzrVWzABvN8Kat2f1n_ZfK0/cara1.jpg?psid=1]
________________________________

**Comment by mtwebster** [comment]
Sorry, yes.

I type it 20 times a day without thinking, but I try to explain it and get it wrong.

**Comment by madrbperu** [comment]
LOL, it happens to the best of us.

Here are the results of the command:

***@***.***:~$ sudo apt remove python3-openssl
[sudo] password for manu:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-cachetools python3-configargparse python3-dateutil python3-fasteners
  python3-google-auth python3-google-auth-httplib2 python3-mock
  python3-monotonic python3-parsedatetime python3-pbr python3-pyasn1
  python3-pyasn1-modules python3-requests-toolbelt python3-rsa
  python3-uritemplate python3-zope.component python3-zope.event
  python3-zope.hookable python3-zope.interface
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  certbot gcalendar python3-acme python3-certbot python3-googleapi
  python3-josepy python3-oauth2client python3-openssl
0 upgraded, 0 newly installed, 8 to remove and 1 not upgraded.
After this operation, 2.502 kB disk space will be freed.
N: Ignoring file 'snappy.prf' in directory '/etc/apt/preferences.d/' as it has an invalid filename extension
Do you want to continue? [Y/n] y
(Reading database ... 646419 files and directories currently installed.)
Removing certbot (0.40.0-1ubuntu0.1) ...
Removing gcalendar (0.4-1) ...
Removing python3-certbot (0.40.0-1ubuntu0.1) ...
Removing python3-acme (1.1.0-1) ...
Removing python3-googleapi (1.7.11-3) ...
Removing python3-josepy (1.2.0-2) ...
Removing python3-oauth2client (4.1.2-5) ...
Removing python3-openssl (19.0.0-1build1) ...
Processing triggers for man-db (2.9.1-1) ...
***@***.***:~$


Guess what....


Manuel A. del Río Bartra
Administrador de Servicios Web
Cel: 976-678-998

[https://n7lpeq.bn1301.livefilestore.com/y2pORGVpGmLJOHcMH123M9KoP3djZkXY5e5P044LqN8X35pUXVdW6T8dTxhOf9L3LczJ-zoeg38SPW4hZ5dz5TihzrVWzABvN8Kat2f1n_ZfK0/cara1.jpg?psid=1]
________________________________

**Comment by madrbperu** [comment]
You are a genius man...!

Thanks(x) + appreciation(∞) = 1000000


Manuel A. del Río Bartra
Administrador de Servicios Web
Cel: 976-678-998

[https://n7lpeq.bn1301.livefilestore.com/y2pORGVpGmLJOHcMH123M9KoP3djZkXY5e5P044LqN8X35pUXVdW6T8dTxhOf9L3LczJ-zoeg38SPW4hZ5dz5TihzrVWzABvN8Kat2f1n_ZfK0/cara1.jpg?psid=1]
________________________________

**Comment by madrbperu** [comment]
But the question remains, I don't recall installing such module, maybe it got installed as a dependency from an unrelated module?

Is there a bug or perhaps a no-no ever installing that python module and messing up other components within the OS?

Should Mint's R&D be notified of this?

Eternally grateful...!


Manuel A. del Río Bartra
Administrador de Servicios Web
Cel: 976-678-998

[https://n7lpeq.bn1301.livefilestore.com/y2pORGVpGmLJOHcMH123M9KoP3djZkXY5e5P044LqN8X35pUXVdW6T8dTxhOf9L3LczJ-zoeg38SPW4hZ5dz5TihzrVWzABvN8Kat2f1n_ZfK0/cara1.jpg?psid=1]
________________________________

**Comment by mtwebster** [comment]
That gcalendar package is what pulled it in, via dependency on something else. Interestingly, gcalendar has the same error when you build/install it from here: https://github.com/slgobinath/gcalendar

It looks like it's a packaging issue in pyOpenSSL
https://askubuntu.com/questions/1428181/module-lib-has-no-attribute-x509-v-flag-cb-issuer-check

I can't reproduce it on Mint 21, so I think we'll just leave it at that.

**Comment by madrbperu** [comment]
Good deal, I'll keep that in mind.

Thanks again...!


Manuel A. del Río Bartra
Administrador de Servicios Web
Cel: 976-678-998

[https://n7lpeq.bn1301.livefilestore.com/y2pORGVpGmLJOHcMH123M9KoP3djZkXY5e5P044LqN8X35pUXVdW6T8dTxhOf9L3LczJ-zoeg38SPW4hZ5dz5TihzrVWzABvN8Kat2f1n_ZfK0/cara1.jpg?psid=1]
________________________________
