### ISSUE TITLE
More Info Button in list view

### ISSUE THREAD

**Issue by lexruee** [linuxmint/mintinstall#36]
In my opinion there should be a button "More Info" when the user selects an entry in the list view.

**Comment by JosephMcc** [comment]
Don't think this is relevant anymore in the new layout in git master.

**Comment by lexruee** [comment]
@JosephMcc 
No problem. 
Since the unity disaster and a tiny excursion to Linux Mint/Cinnamon in 2013, I went back to the roots, namely Debian with Gnome 3 :smile:. 

Anyways, keep up the good work with the UI/UX of Linux Mint/Cinnamon :-).

Cheers
