### ISSUE TITLE
[Feature Request]  Option to pick native or Flatpak versions of Apps

### ISSUE THREAD

**Issue by Xmetalfanx** [linuxmint/mintinstall#361]
Please forgive me if this is off topic (i think Git 'issues' are more for issues or problems) but I just switched an  install from PopOS to Mint Cinnamon and in Popshop (PopOS's software manager)  https://github.com/pop-os/shop they have an option  like right to the left of the install button where you can basically select what version of a package is installed by default and even an option to set what you want as default) .... say "Flatpak vs native app" .... the flatpak sometimes being newer.

I DO KNOW this would only be a thing on select packages and the time it would take ot add this may not be worth it to the Mint team .. just thought it maybe a neat addition to have in the software center ... not sure how that may effect how Mint has a seperate section for Flatpaks if it all.

**Comment by mtwebster** [comment]
What Mint version are you on? The latest Mintinstall does this:
![Screenshot from 2023-03-01 16-18-23](https://user-images.githubusercontent.com/262776/222267516-6fafa7f6-d453-4ad1-a3c6-8fec7dd7a3e5.png)

**Comment by Xmetalfanx** [comment]
oh darn i didn't see that ... sorry for wasting your time (21.1 and i was looking in the wrong spot... i see it here now)
