### ISSUE TITLE
Flatpak tab doesn't load app icons

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mintinstall#373]
mintinstall 8.2.4

![ffllpp](https://github.com/linuxmint/mintinstall/assets/68134588/1ed33329-080a-4be5-bd55-8010f42ef230)
Even refreshing the package list there are no changes

terminal ouput:

> h2gn@h2gn:~$ mintinstall
MintInstall: Detected system architecture: 'x86_64'
MintInstall: No new reviews
MintInstall: Deleting old screenshots
mint-common (WARN): Could not load appstream info for remote '<Flatpak.Remote object at 0x7f66610a2d40 (FlatpakRemote at 0x55a453d10a10)>': as-store-error-quark: Failed to parse XML: Error on line 1960 char 29: <p> already set '
      Organic Maps is a free Android & iOS offline maps app for travelers,
      tourists, hikers, and cyclists.
      It uses crowd-sourced OpenStreetMap data and is developed with love by
      ' and tried to replace with ' (' (0)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/mintcommon/issues/56

There's a fix for appstream-glib in Ubuntu's proposed repos, which fixes this. Just waiting for it to be approved.

**Comment by haggen88** [comment]
@mtwebster 
I confirm that most app icons are now loaded correctly in the Flatpak tab [only problems with qgis desktop and Draw.io].
