### ISSUE TITLE
Regression: list of keyboards is now in english instead of being in french

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mintinstall#380]
After choosing language **Français**:

![installation Linux Mint_2](https://github.com/linuxmint/mintinstall/assets/3955499/da314950-43b2-4195-8246-d1278abe4ef0)

The list of keyboards is in english, it isn't tranlated anymore:

![installation Linux Mint_3](https://github.com/linuxmint/mintinstall/assets/3955499/a2da991a-0eee-4e71-a305-fee4bf056a44)

It was in translated in french in older versions:

![installation Linux Mint_3-old](https://github.com/linuxmint/mintinstall/assets/3955499/d9edd7ab-8d0a-4302-bf74-6514acdacfa1)

**Comment by clefebvre** [comment]
Ok, that's in ubiquity. It's actually a bug fix for another issue. I'll close this for now because it won't change in 22.x and we'll move to live-installer in 23.

**Comment by InfoLibre** [comment]
It will not be fixed as Ubiquity is now unmaintained and replaced by Calamares starting with Ubuntu 24.04 LTS.
