### ISSUE TITLE
[Request] Add Vivaldi Browser to Software Manager

### ISSUE THREAD

**Issue by GwenDragon** [linuxmint/mintinstall#392]
Can you add Vivaldi browser to Software Manager?
You have so many free browsers in your list.
Please contact Vivaldi at https://vivaldi.com/partners/linux/

**Comment by marco4mp** [comment]
I don't think it's a good idea, for the following reasons:

1. Most of the "deb" apps that you find in the Linux Mint Software Manager come from the Ubuntu repository.
2. Vivaldi is not an OpenSource browser, so I don't think it's worth the extra effort to include it in Mint's own repository.
3. If the Vivaldi team creates an option in Flatpak/Flathub, it will automatically appear in the Mint Software Manager.


(Sorry for my grammar, I'm not a native English speaker)

**Comment by marco4mp** [comment]
I don't think it's the Mint team's job to include that browser.
Most apps (and browsers) that can be downloaded from the Mint Software Manager come from the Ubuntu repository (deb) and Flathub (Flatpak).

If the Vivaldi team publishes an option on Flathub, it will automatically appear in the Software Manager.

**Comment by GwenDragon** [comment]
OK. Then i close this issue.

**Comment by marco4mp** [comment]
Vivaldi is now available on Flathub!

**Comment by GwenDragon** [comment]
I hope, after it is on Flathub, there will be a chance to get it in Mint Software Manager in some months.

**Comment by riomccloud** [comment]
> I hope, after it is on Flathub, there will be a chance to get it in Mint Software Manager in some months.

When an app goes to Flathub, it's automatically available on Mint Software Manager, since it can download apps from there.

**Comment by marco4mp** [comment]
@GwenDragon Hi, I think it's time to close this report.
