### ISSUE TITLE
mintinstall: search is limited to the active category

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mintinstall#401]
When I choose a category and then, search a software by its name, in the search bar, I can't find the software if it's not in the active category. I must go back to the home page of mintinstall and search again.
Search in the search bar should be independent from the active category, it should always works in all the categories.

**Comment by umikali222** [comment]
If you only want to search in the category, then you would want it not to be independent from the category.
If you would want to search all of the apps, you would go back to the main menu and search in there

**Comment by Ensam57** [comment]
Indeed. But usually, in all search engines, we do a research in all categories, by default. Research limited to a specific category is done sometimes with filters system. So, it would be better to have by default a research in all the database, not limited to a category.

**Comment by mtwebster** [comment]
![image](https://github.com/user-attachments/assets/b1a5977e-115d-45da-aff3-5c7461ba2d10)

This button allows you to specify whether you want to search the current category only (enabled), or to always have a global search.
