### ISSUE TITLE
[Feature Request] List of all installed dpkg/flatpak packages from the command line interface

### ISSUE THREAD

**Issue by mortim** [linuxmint/mintinstall#402]
Hi, I think it's interesting to detect all dpkg/flatpak apps (available in the software manager) but installed from the terminal.

**Comment by mtwebster** [comment]
The 'Show installed applications' option in the menu lists anything the user has installed explicitly. It doesn't include dependencies pulled in as a result.

Any flatpak installed in the terminal will be detected by Mintinstall. If it's from a foreign repo (not flathub or something previously set up), it may take a cache refresh for it to show *all* info, like descriptions, but it should show up regardless.

There's also a commandline option (that I just [fixed](https://github.com/linuxmint/mintinstall/commit/c052c13b9fadc6fb4571e52e2b1f2b8aa991eea3) that will list all packages and their states - 

```bash
LANGUAGE=C /usr/lib/linuxmint/mintinstall/mintinstall.py list
# and also
LANGUAGE=C /usr/lib/linuxmint/mintinstall/mintinstall.py list-flatpak
```

This will be working again in the next release. It lists all packages with basic info, including the categories they are in (including the 'installed' category).
