### ISSUE TITLE
Unexpected error appears when installing app from Software manager on Linux Mint

### ISSUE THREAD

**Issue by JuraLys** [linuxmint/mintinstall#406]
Mint 21.3 mate
open Software manager on Linux Mint and search Download word
click found app title and click Install button, see screenshots
![mint-soft-install-hang(](https://github.com/linuxmint/mintinstall/assets/146434286/e6a8f2de-e9cb-4c5f-aadc-efcaf910e912)
![mint-soft-install(](https://github.com/linuxmint/mintinstall/assets/146434286/e907bd54-7bc0-4cab-a7cd-85a0deeba9c3)

**Comment by marco4mp** [comment]
@JuraLys  Have you tried it lately? I don't have that problem.

**Comment by JuraLys** [comment]
> @JuraLys Have you tried again? I don't have that problem.

I deleted Linux Mint VM

**Comment by mtwebster** [comment]
Flathub website issue.
