### ISSUE TITLE
Application is unresponsive at launch and eventually produces a 'not responding' message

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintinstall#407]
What I did. I launched mintinstall, via GUI (from the main menu), on a machine that has been upgraded to Mint 21.3; I had not opened mintinstall on this computer for a long time.

What happened. Seemingly nothing happened for a few seconds, then an icon appeared within my dock - Plank - then the icon disappeared, then it reappeared and then a window appeared; when I tried to maximize the window, a pop-up informed me that the application was not responding.

What I expected. Few people use Plank on Mint, but, at the least mintinstall should not produce an error message about responsiveness / i.e. it should be responsive. That said, being unresponsive is alright, so long as the user is told to wait. Note that many a user of mintinstall is a _new_ user.

Other information. The PC at issue is somewhat slow, but it does fine with most other things. (It is a ThinkPad X230, with a dual-core processor, a SATA III SSD, Intel graphics, and 8GB of RAM; and there is plenty of drive space left and the computer was not under load from any other program.)

Cf. and also #301 and #306 and perhaps also #40 and #351.

**Comment by clefebvre** [comment]
This is fixed on git master.
