### ISSUE TITLE
[Feature request] Export/import all flatpaks & their data

### ISSUE THREAD

**Issue by mildly-useful** [linuxmint/mintinstall#411]
I know that through the terminal we have commands like create-usb (which works only for 1 app, so it's cumbersome if you have many flatpaks), and I also know that we can simply copy the flatpak app & preferences folders manually. 

But, wouldn't it be nice to have a single button (in the Software Manager) to export or import all your installed flatpaks? It would be a really neat feature, and it can make migrating all your installed flatpaks, their dependencies, and their preferences/saved data, super easy and fast. It would also be a good backup solution, and also a nice & easy way to preserve old software versions.

**Comment by clefebvre** [comment]
Yes, but that's way beyond the scope of mintinstall. This would be better in flatpak itself or a 3rd party flatpak utility.
