### ISSUE TITLE
Add more alternative browsers to Application Manager

### ISSUE THREAD

**Issue by Dan-cer** [linuxmint/mintinstall#414]
I still prefer normal packages instead of flatpak. That is why I make this feature request: 
Add browser like Opera or Vivaldi or some others to the list in Application Manager. There are quite a few visible already if I would run the manager incl. flatpaks. But I have removed it (to make starting of Application Manager way more fast than with flatpaks in it).

Linux Mint / Ubuntu might feature Firefox and Chromium-browser. However, there should be more alternatives listed beside them.
Not only as flatpaks.
Thank you in advance!

**Comment by mtwebster** [comment]
This is the whole point of Flatpaks - to give you alternatives. It'd be great to have more accessible ones, but it's up to those folks to do the process to get them added to ubuntu (or more likely, Debian->Ubuntu). Some of them already build 'deb' packages, but you have to go to their website to get them - Opera and Vivaldi are both this way.

Having once attempted to get a package of mine into Debian, I really can't blame them for not trying do add theirs.
