### ISSUE TITLE
Minimal Install

### ISSUE THREAD

**Issue by iamdtms** [linuxmint/mintinstall#420]
Looking forward to have only the require packages installed. Like a minimal setup. 

Normal & Minimal install already took shape in an "another" distribution:
https://ubuntu.com/tutorials/install-ubuntu-desktop#5-installation-setup

**Comment by clefebvre** [comment]
Sorry, we've no plans to support this. Mint tries to be an out-of-the-box finely tuned experience.

**Comment by iamdtms** [comment]
Quite understandable, thank you for letting me know.
