### ISSUE TITLE
Add option not to show flatpaks

### ISSUE THREAD

**Issue by archisman-panigrahi** [linuxmint/mintinstall#421]
I want to use some flatpaks and not remove them entirely, but I want the graphical package managers to preferably show apt apps before flatpak, or not show flatpak at all.

I suggest we add an option not to show flatpak apps. The Manjaro's store (Pamac) has a similar feature.

Reason: I and my family use some computers with small amount of non-upgradable storage (32 GB). Since flatpak consumes a lot of storage compared to their APT counterparts, I don't want to use flatpak unless there is an APT alternative. While I can use the command line/search for non-flatpak apps in the app store, some of my family members (who are the primary users of these computers) prefer to install the first app that is offered to them after searching the appstore (these are flatpak apps). To save storage, I would like to either

1. Turn off flatpak search support in the app store.
2. Or, show flatpak apps only when some flatpak option is enabled.

Is this possible to implement?

**Comment by clefebvre** [comment]
![image](https://github.com/linuxmint/mintinstall/assets/1138515/603a1122-c5cd-4b36-b9a4-6c60dd3ed467)

It's coming. This is the git master version right now.
