### ISSUE TITLE
No search bar

### ISSUE THREAD

**Issue by pucelev** [linuxmint/mintinstall#428]
Upgraded from Mint Cinnamon 21.3 to Cinnamon 22.  Software Manager (mintinstal 8.3.2) has no search bar or settings.  See attached file.
![Mintinstall_have](https://github.com/user-attachments/assets/ba6b8903-f662-48fe-9752-5762c92b93d8)

**Comment by mtwebster** [comment]
Do you have some plugin or extension that disables client-decorations in windows? If so, that's your issue.
