### ISSUE TITLE
On a new PC, searching for 'chome' produces a slew of results non of which are are Google Chrome

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintinstall#441]
Upon installing Mint (Cinnamon), I did tick the 'non-free' option.

![image](https://github.com/user-attachments/assets/5164082e-715a-4451-86cd-bf500e3c8e5b)

Perhaps you can reproduce the issue.

**Comment by JosephMcc** [comment]
Chrome isn't in the repos, so it won't show up there.
