### ISSUE TITLE
Mint Software Manager messes up permissions on /run/user/1000/dconf/user

### ISSUE THREAD

**Issue by catalin-hritcu** [linuxmint/mintinstall#52]
It seems that simply starting the Mint Software Manager (gksu mintinstall) messes up the permissions on /run/user/1000/dconf/user, by changing its ownership to root. This has negative consequences for many other programs running on the same machine: mate-settings-daemon, nm-applet, emacs, mate-power-manager, etc, who display the following error message:

```
(mate-settings-daemon:4602): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.
```

Some of these other programs exhibit extremely serious side effects. For instance, mate-settings-daemon with the wrong permissions takes up 100% of 1 CPU, 6GB of RAM, and >300MB of logged errors in .xsessions, rendering some machines close to impossible to use (see https://github.com/mate-desktop/mate-settings-daemon/issues/44 for more details on this one).

I can reliably reproduce this problem on a fresh install of LMDE 201403.

**Comment by manish-rajora** [comment]
I am facing in Linux Mint 18 'Sarah' "MATE-64 bit".
In my case if i run apt 
(mate-terminal:2370): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.
message reappear and chock the ram till end .

**Comment by monsta** [comment]
Probably because systemd isn't patched anymore in Mint 18 (as opposed to Mint 17 and LMDE Betsy).

**Comment by manish-rajora** [comment]
I asked linux-mint guys on irc chat they told me to not use apt instead use update manager to update the system, and they suggested me a fresh install, with linux mint sarah KDE 64 bit so i did and till now no issue faced, so i think there is something wrong introduced by me while i installed things from apt.
Thanks for help.

**Comment by clefebvre** [comment]
I'm not sure why they told you that. It's a good idea to use the Update Manager so you can "review" updates, but other than that, there's no issue with using apt directly, and it certainly won't affect your runtime directory.

The issue is related to running processes as root.

**Comment by ACinnamonUserInUK** [comment]
I have this problem on Mint 18.1 x64 Cinnamon. It seems to be preventing me from logging in sometimes, and it thrashes the disk like crazy. Is there a fix or workaround please? Also, compare [this Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=732209).

I note that the ostensible workaround mentioned in this thread above is . . to remove systemd. That is rather drastic.

**Comment by Marian-Rio** [comment]
Hello I just installed Linux Mint Cinnamon and I am new on Linux, I use at start the terminal and administration configure the firewall installed a program through terminal but suddenly I start having the error that my authentication was unsuccessful even on terminal says I am not allowed, I can not access Administration and basically do nothing more as I have no more access I am not sure what caused that I am not allowed also to adduser so wondering is I need reinstall the system or there is any place maybe in /run/NetworkManager/resolv.config? Thansk thanks Mariana
