### ISSUE TITLE
If package installation fails to start due to lost internet connection, the "Install" button doesn't re-appear

### ISSUE THREAD

**Issue by veikk0** [linuxmint/mintinstall#70]
Linux Mint 17, mintInstall 7.5.7.

If the installation of a package fails to start due to the lack of an internet connection, right after you've clicked the "Install" button on a package's description page, the button doesn't re-appear so one could try again. This only happens under one, specific circumstance, however: when mintInstall was opened when there was an internet connection, and there is no connection when the user clicks the "Install" button.

How to reproduce:

Open mintInstall with an internet connection. Navigate to a package's description page, such as to Fonts -> fonts-cantarell. Now disconnect your machine from the internet (turn off your wired of wireless from Cinnamon's Network Manager applet), and click the "Install" button. You'll see an error pop up, and note that the "Install" button is now gone, even though it would normally return after a failed install.

Quite a specific circumstance, I know, but I decided to report it nevertheless. I discovered it because my router is provided a connection by a USB mobile broadband adapter, and the connection isn't always stable. I could also see this as an issue when the wireless signal is weak.

**Comment by clefebvre** [comment]
Following the recent mintinstall revamp on git master, the UI was redesigned, so this can be closed.
