### ISSUE TITLE
mintinstall freezes during installation software

### ISSUE THREAD

**Issue by Morfeusz888** [linuxmint/mintinstall#74]
mintinstall freezes during installation software. The problem is as follows:
1. I note 10 applications to be installed in mintinstall.
2. mintinstall start installation of the application.
3. At some point mintinstall freeze when installing applications.
4. The list of applications is still visible, but still progress bars indicate 0%

I noticed that the problem occurs with software that has a lot of dependencies, eg. Nautilus installed in kde environment.

I put a log of the application mintinstall and work of this program is stopped at this point:

SystemError: E:Could not open file /var/lib/apt/lists/packages.linuxmint.com_dists_qiana_main_binary-amd64_Packages - open (24: Too many open files)

Unfortunately, you can not resume the suspended installation. It should kill the process and run the program again. The error was repeated by me on two computers.

Logs -> https://launchpadlibrarian.net/185576625/mintinstall_log.txt

BTW. The problem also reported on Launchpad, but no one probably does not respond.

Details about the system:

Distributor ID: LinuxMint
Description: Linux Mint 17 Qiana
Release: 17
Codename: qiana
GUI: KDE
Architecture: 64-bit

**Comment by kelebek333** [comment]
Python-apt fixed on version python-apt_1.0.0~beta3.

apt/cache.py: Work around a cyclic reference from Cache to its methods    (Closes: #745487)

It maybe come for LMDE from repo after testing on sid. But what will happen for the Linux Mint 17.x?

**Comment by clefebvre** [comment]
Backend switched to aptdaemon on git master.

**Comment by blackpoint200** [comment]
Mintinstall 7.9.7 still has this bug. Not only it freezes during installation but also causes system to temporary freeze and then you can't switch grouped windows with mouse. Only Alt-Tab is working. You have to restart Cinnamon.
