### ISSUE TITLE
mintinstall allows you to install duplicates

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintinstall#76]
If you click to install a package the install button disappears, then go back in the navigation tree and then click on the same package, the install button will reappear.

**Comment by xenopeek** [comment]
This can be reproduced on Linux Mint 18. For example with gedit:

1. search for gedit
2. double-click on gedit in the search results to go to its detail page
3. click the install button
4. don't wait for completion but go back to the search results and double-click gedit again (before the installation progress bar reaches the end)
5. you'll end up on the details page and the install button will be displayed after installation completes

**Comment by clefebvre** [comment]
This should be fine with the UI revamp.
