### ISSUE TITLE
Software Manager in KDE contains visual flaws

### ISSUE THREAD

**Issue by jebeld17** [linuxmint/mintinstall#78]
Linux Mint 17 KDE Edition
mintInstall 7.5.7

It's been years now since the Linux Mint Software Manager was branched and implemented into the common Linux Mint versions, and yes leaps and bounds have been made to improve stability but during that time, precise attention to visual details and GTK artifacts in the Software Manager (mintInstall 7.5.7) have been looked too quickly over and ignored for too long now.
We need a visual makeover - Something that stands out from the crowd - in a good way, not further continuing to let the aesthetic nightmare get worse and worse as new GTK and Qt versions evolve... Right now, it appears as a blocky, blotchy mess: Some colors and gradients are made to fit the Qt/KDE ecosystem while the buttons, explorer bars, and some text areas mimic the bland and grey look and feel of GTK from back in 2007 or so. The buttons are outdated and don't match the current "flat-but-bold-and-eye-popping" 2014 UI standards seen in every other OS including Ubuntu yet rather closely resemble the much outdated and overused Mac OS X "Aqua" look from OS X 10.2.

My apologies, but everything about it just seems ... wrong and out of place. A fix needs to happen, Linux Mint is designed to be the *true* Linux for everyone, something that everyone will understand, love, and enjoy to work with rather than appearing similar to an outdated office computer.

![snapshot1](https://cloud.githubusercontent.com/assets/9492083/4870332/a10207ec-6162-11e4-8b81-622456611765.png)
![snapshot2](https://cloud.githubusercontent.com/assets/9492083/4870333/a103d8e2-6162-11e4-8105-377c86e36b9a.png)
![snapshot3](https://cloud.githubusercontent.com/assets/9492083/4870334/a107fd00-6162-11e4-8307-d26320bde1d1.png)

**Comment by xenopeek** [comment]
I suggest this one can be closed. This is more a comment on Gtk theme integration (or lack thereof) on Linux Mint 17 KDE than on Software Manager. For Linux Mint 18 KDE—while one can still see it is a Gtk application—Software Manager uses the same colors and general look as Qt applications.
