### ISSUE TITLE
Linux Mint 17.1 Software Manager RUN button.

### ISSUE THREAD

**Issue by Olotila** [linuxmint/mintinstall#79]
Hello,

I like Linux Mint very much; I have been using it for about a year now in an occasional manner. I have it in my secondary laptop and in a virtual machine. I sometimes install it for my friends and relatives. I teach Linux in a vocational school. I promote the use of Linux. We sell Linux Mint machines in our school shop, set up by my students.

I frequently install and test new apps. I search, install, test and then remove or keep them (app names usually don’t tell me anything, I don’t remember them, good example are kids games etc). This is not a very user friendly process because of the lack of RUN button. It is annoying as hell to always search for the app from menu or type it to search bar especially if you forget the name of the app before you end typing the name of the app. Worse, you might have use the terminal in order to start the app.

Linux Mint promotes ease of use. Which is easiest: click the RUN button once, search for the app from the menu, type its name into search bar or launch it from terminal?

Two questions:
1.  Why Mac App Store, IOS App Store, Microsoft Store, Android Play … etc do have RUN button (or similar function) next to a freshly installed app?
2.  Why Linux Mint Software Manager does not have RUN button (or similar function) next to a freshly installed app?

I really hope the RUN button will be implemented in some near future.

(Original thread in http://forums.linuxmint.com/viewtopic.php?f=29&t=184106&sid=c90aca10c720e18f5cc1542544f4640d)

**Comment by monsta** [comment]
@clefebvre: I guess this is implemented now in https://github.com/linuxmint/mintinstall/commit/828e5ca90d61f67667d65d7220bedb23fb176178?

**Comment by JosephMcc** [comment]
Yes it is.
