### ISSUE TITLE
Misbehaving with fingerprint reader.

### ISSUE THREAD

**Issue by jackmatt2** [linuxmint/mintinstall#80]
I use fprintd. When I start mintinstall.
1. The light on the fingerprint reader will start flashing indicating that the program needs authentication, however, other than that nothing tells me that authentication is needed. No dialog or anything.
2. fprintd is a bit sensitive, it is quite common that I will swipe three times and fail each time which will then revert to a fallback manual password mode. The problem with "mintinstall" is that if the fingerprint scanner fails three times to authenticate nothing is displayed at all, I never get the opportunity to manually enter my password. I have to load the application again and hope the scanner works.

**Comment by RavetcoFX** [comment]
Are you able to try the latest GIT version and see if this still happens, also does synaptic work properly?

**Comment by clefebvre** [comment]
This should be fine now that we run in user mode (on git master).
