### ISSUE TITLE
 Translation: Some strings need to be fetched with ngettext

### ISSUE THREAD

**Issue by gunchleoc** [linuxmint/mintinstall#87]
Please fetch the following strings with ngettext, so that they can be translated properly:

```
%d ongoing actions
```

Located in: usr/lib/linuxmint/mintInstall/mintinstall.py:301

```
%d packages are currently available
```

Located in: usr/lib/linuxmint/mintInstall/mintinstall.py:591

```
%d reviews
```

Located in: usr/lib/linuxmint/mintInstall/mintinstall.py:1380 usr/lib/linuxmint/mintInstall/mintinstall.py:1853

```
%d packages
```

Located in: usr/lib/linuxmint/mintInstall/mintinstall.py:1416

```
Gathering information for %d packages...
```

Located in: usr/lib/linuxmint/mintInstall/splash.py:28

Related bug on Launchpad: https://bugs.launchpad.net/linuxmint/+bug/1390481

Thank you :)

**Comment by NikoKrause** [comment]
I'll create a fix for that soon. Probably tomorrow.
If you have found more strings, which need ngettext, let me know.

**Comment by gunchleoc** [comment]
Thanks for taking this on :)

Maybe grep for %d to check if I've missed some? Is will go faster than checking manually, and I don't have access to Linux ATM.

**Comment by NikoKrause** [comment]
mintinstall has experienced bigger changes now. Those strings are outdated.

@JosephMcc 
This can be closed.

**Comment by JosephMcc** [comment]
Ok, we can review this again once the changes are done.
