### ISSUE TITLE
Open PPA feature only shows not-installed packages

### ISSUE THREAD

**Issue by rkingsbury** [linuxmint/mintinstall#88]
I love the new "Open PPA" features that's available in Cinnamon 2.6. It's really helpful to be able to see exactly which packages are coming from a specific PPA. However, it appears that it only lists packages from the PPA that are **not installed**.  Was this intentional?  I would find it more helpful to be able to see **all** packages in a PPA, especially the ones that I have already installed.

**Comment by xenopeek** [comment]
This is an issue for mintsources (Software Sources). As it isn't about Software Manager I suggest closing it here.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mintsources/issues
