### ISSUE TITLE
Shell Commands execute when searching

### ISSUE THREAD

**Issue by TheRegRunner** [linuxmint/mintinstall#90]
![screenshot](https://cloud.githubusercontent.com/assets/13422603/8864577/e6e46162-31a3-11e5-8f02-befac52cb285.png)
type in 
mintInstall -d
enter the password
go to APT search field and seach for this text  

$(xterm)

Now  xterm will start as root  !!

mintInstall uses os,system() so it executes shell commands injected in the textfield

os.system("/usr/bin/mint-show-apt " + textfield.get_text() + " &")

**Comment by xenopeek** [comment]
This has been solved from at least mintinstall 7.7.3. Issue can be closed.
