### ISSUE TITLE
Invalid package name error message is not translated

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/mintinstall#91]
Leaving comment for package that is not in default repositories we got:
"Invalid package name
The package you're trying to review was not found in our database. Please contact the development team about this." error messages. But it is not localisable.
![kepernyokep 2015-08-23 13 51 26](https://cloud.githubusercontent.com/assets/5292264/9428451/d167e49e-49ae-11e5-87fb-946a64ced4be.png)

**Comment by Vahan86** [comment]
@KAMI911, is this still an issue in Mint 18 (Cinnamon 3.0)?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by KAMI911** [comment]
It seems this message is not localisable. Also there is a same message with invalid password is not translatable, please repoen it.
