### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by callagg2** [linuxmint/mintinstall#93]
In the Software Manager, if I go to install say Mintmenu, on the far right, it says "Score:" on one line, then underneath the star rating, number of reviews, and 238 .
Should it be "Score: 238" on one line and then the star rating, number of reviews direcly underneath to show the strength of that score?
![mintmenu](https://cloud.githubusercontent.com/assets/15323690/10729311/61016fcc-7be0-11e5-8c88-6f3ece1242c3.png)

In the Software Manager, at the bottom it shows a gear cog and the words "No ongoing actions". Should these words not be greyed/faded to show them as inactive on first entering the Software Manager, and remain faded until after you have actually finished installing something. 

Also if I perform a search for some obscure program, there is no message to tell me that program is not found in the Manager. Should the text "No ongoing actions" not change to say "Searching" when you hit the search magnifying glass and then to say "Program Not Found", rather than remaining at "No ongoing actions".

**Comment by callagg2** [comment]
In Software Manager, under Sound and Video, can the various plugins not be relegated to subcategories within the parent program. 

So, if i go to install xbmc-bin, when i click on XBMC within Sound and Video, it brings me to the next screen where at that point, I can install 
- the bin program or
- plugins such as xbmx-eventsclients-common, xbmc-eventclients-j2me and so on 

This would reduce the clutter under the Sound and Video category. 

![kodi](https://cloud.githubusercontent.com/assets/15323690/10729440/307f9a62-7be1-11e5-8e3a-2ae00ca5cc82.png)

**Comment by callagg2** [comment]
In mintinstall 7.7.5

Upon opening, the list of categories on the home page, 
The category "Sound and video" has a small "v" for video yet
the category "Science and Education" has a capital "E" for Education.
Is this not capitalising not inconsistent?

**Comment by callagg2** [comment]
In mintinstall 7.7.5

I think there should be developer feedback within the comments sections of the Software Manager. For example, if we look at "Redshift" in the mintinstall, we can see that on October 19, 2016, a user left a comment saying that Redshift only works after you install it if you ALSO install geclue2-0.  This comment was great for users like me to see and follow, but do we have any idea if the developer sees it and includes the dependency at the next update.

**Comment by callagg2** [comment]
In mintinstall 7.7.5
In the "Search results" page, would it be possible, we could have a "install/uninstall"  toggle button to the right of the program's rating? I know many people like to go in and read the details of the program before updating, but for those of us that install the same programs every version of Mint, we don't need to have to read the details again. Simply hitting an "install" button at the "Search results" page would suffice.

**Comment by callagg2** [comment]
In mintinstall 7.7.5
Should there be a facility to sort programs/packages by name rather than by ranking/rating?

**Comment by callagg2** [comment]
In mintinstall 7.7.5
Can we have a facility to filter out packages that maybe are designed for kde etc.
For example, if i feel that i would only install GTK programs on my computer i can see no way currently of specifying only such programs to appear in a search.

**Comment by callagg2** [comment]
In mintinstall 7.7.5
Inconsistency between the About (Help) page on Mint Programs.

In Pix, xed and xplayer, when i select help and then About, it gives me a website link, which after clicking it brings me to the relevant point on github.
But in mintinstall, there is no such website link. I think there should be one for consistency.

Actually, Pix also has the line "Copyright © 2001-2010 Free Software Foundation, Inc." which none of the rest have. 

Furthermore, Pix and xed have a line explaining what the programs do, but xplayer does not. For consistency, it should do.

**Comment by callagg2** [comment]
In mintinstall 7.7.5
I'm not sure how visually this would look, and i know it would be inconsistent with Nemo, so maybe it's a nonstarter...
If i've clicked into the category "Office", in the top left it says "Categories>Office" and then if i click say libreoffice-writer, it will say "Categories>Office>libreoffice-writer" but as there is no "back" arrow that i can see, should we not reverse the arrows in the top left so we are writing "Categories<Office"  and "Categories<Office<libreoffice-writer"  so people know to click the previous entry in the top left to back a page?

**Comment by JosephMcc** [comment]
The UI has seen a complete overhaul in git master. I'm closing this since many of the listed issues are no longer relevant. Also in the future, please open one issue per problem. Don't lump them all under a single issue.
