### ISSUE TITLE
Add 'Platform' games category

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintinstall#97]
It would be useful to create a 'Platform' games category to include games like supertux, teeworlds, xmoto, alex4, smc.

In order to make room for this new category, it would be good to combine 'Real-time strategy' and 'Turn-based strategy' into a single category called 'Strategy'.

https://en.wikipedia.org/wiki/Platform_game

**Comment by xenopeek** [comment]
The categories for a package are set by the package maintainer and there are a limited number of registered categories (see https://standards.freedesktop.org/menu-spec/latest/apa.html) and 'Platform' isn't on those. This would require a change in upstream distributions as these games come from the Ubuntu or Debian package base repositories and likely a change in the linked specification. I don't think this can be implemented from mintinstall.

Debian have an alternative called "Debtags" (see FAQ on https://wiki.debian.org/Debtags) with a wider selection of categories (which include 'Platform') but it's not widely used and not viable to be used in mintinstall as it doesn't work with the package management system used by mintinstall.
