### ISSUE TITLE
Improve categorized games

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintinstall#98]
Was browsing through the software manager and noticed these improvements that could be made to the categorized games.

**First-person shooters**
Minetest shouldnt be listed
redeclipse not listed
Chocolate Doom not listed
PrBoom+ not listed
Doomsday
dhewm3 not listed if in repo (in getdeb)
GZDoom not listed if in repo (in getdeb)
Xonotic not listed if in repo (in getdeb)
Unvanquished not listed if in repo (in getdeb)
UrbanTerror not listed if in repo (in getdeb)
World of Padman not listed if in repo (in getdeb)

**Real-time strategy**
0AD not listed

**Emulators**
pcsxr not listed
mupen64plus not listed
vbaexpress not listed
mame not listed
mess not listed
gens not listed if in repo (in getdeb)
gens-gs not listed if in repo (in getdeb)
vbam not listed if in repo (in getdeb)

**Comment by xenopeek** [comment]
Same comment as on your issue #97. For categories available on https://standards.freedesktop.org/menu-spec/latest/apa.html you could request the maintainers of these packages to amend the category.
